Repository runtimeverification/kontrol, pull requests merged in 2023-10, with the labels that each got.

#48 Migrate missing tests to kontrol
  .github/workflows/test-pr.yml
  package/version
  pyproject.toml
  src/tests/integration/test-data/contracts.k.expected
  src/tests/integration/test-data/foundry.k.expected
  src/tests/integration/test-data/foundry/src/KEVMCheats.sol
  src/tests/integration/test-data/foundry/test/Ambiguous.t.sol
  src/tests/integration/test-data/foundry/test/FreshInt.t.sol
  src/tests/integration/test-data/foundry/test/StoreTest.t.sol
  src/tests/integration/test-data/foundry/test/file.txt
  src/tests/integration/test-data/foundry/test/myscript.sh
  src/tests/integration/test-data/foundry/test/script.sh
  src/tests/integration/test-data/gas-abstraction.expected
  src/tests/integration/test-data/lemmas.k
  src/tests/integration/test-data/show/AssertTest.testFail_assert_false().expected
  src/tests/integration/test-data/show/AssertTest.testFail_assert_true().expected
  src/tests/integration/test-data/show/AssertTest.testFail_expect_revert().expected
  src/tests/integration/test-data/show/AssertTest.test_assert_false().expected
  src/tests/integration/test-data/show/AssertTest.test_assert_true().expected
  src/tests/integration/test-data/show/AssertTest.test_failing_branch(uint256).expected
  src/tests/integration/test-data/show/AssertTest.test_revert_branch(uint256,uint256).expected
  src/tests/integration/test-data/show/AssumeTest.testFail_assume_false(uint256,uint256).expected
  src/tests/integration/test-data/show/AssumeTest.testFail_assume_true(uint256,uint256).expected
  src/tests/integration/test-data/show/AssumeTest.test_assume_false(uint256,uint256).expected
  src/tests/integration/test-data/show/LoopsTest.sum_N(uint256).expected
  src/tests/integration/test-data/show/SetUpDeployTest.test_extcodesize().expected
  src/tests/integration/test_foundry_prove.py
  src/tests/profiling/test_foundry_prove.py
Labels: automerge

#68 Update dependency: deps/kevm_release
  deps/kevm_release
  flake.lock
  flake.nix
  package/version
  poetry.lock
  pyproject.toml
Labels: automerge

#63 Refactor proof setup
  .github/workflows/test-pr.yml
  package/version
  pyproject.toml
  src/kontrol/__main__.py
  src/kontrol/foundry.py
  src/kontrol/prove.py
Labels: automerge

#81 Use fast CI machines for proof tests
  .github/workflows/test-pr.yml
  package/version
  pyproject.toml
  src/kontrol/__init__.py
Labels: automerge

#82 Update dependency: deps/kevm_release
  deps/kevm_release
  flake.lock
  flake.nix
  package/version
  poetry.lock
  pyproject.toml
  src/kontrol/__init__.py
Labels: automerge

#88 Clarify `--test` functionality for kontrol prove
  package/version
  pyproject.toml
  src/kontrol/__init__.py
  src/kontrol/__main__.py
  src/kontrol/foundry.py
Labels: automerge

#87 Update dependency: deps/kevm_release
  deps/kevm_release
  flake.lock
  flake.nix
  package/version
  poetry.lock
  pyproject.toml
  src/kontrol/__init__.py
Labels: automerge

#94 Update dependency: deps/kevm_release
  deps/k_release
  deps/kevm_release
  flake.lock
  flake.nix
  package/version
  poetry.lock
  pyproject.toml
  src/kontrol/__init__.py
  src/tests/integration/test-data/gas-abstraction.expected
  src/tests/integration/test-data/show/LoopsTest.sum_N(uint256).expected
Labels: automerge

#54 Execution of contract initialization code
  package/version
  pyproject.toml
  src/kontrol/__init__.py
  src/kontrol/__main__.py
  src/kontrol/foundry.py
  src/kontrol/prove.py
  src/kontrol/solc_to_k.py
  src/tests/integration/test-data/contracts.k.expected
  src/tests/integration/test-data/foundry.k.expected
  src/tests/integration/test-data/foundry/test/InitCode.t.sol
  src/tests/integration/test-data/foundry/test/InitCodeBranch.t.sol
  src/tests/integration/test-data/foundry/test/Merge.t.sol
  src/tests/integration/test-data/foundry/test/Simple.t.sol
  src/tests/integration/test-data/show/AssertTest.testFail_assert_false().expected
  src/tests/integration/test-data/show/AssertTest.testFail_assert_true().expected
  src/tests/integration/test-data/show/AssertTest.testFail_expect_revert().expected
  src/tests/integration/test-data/show/AssertTest.test_assert_false().expected
  src/tests/integration/test-data/show/AssertTest.test_assert_true().expected
  src/tests/integration/test-data/show/AssertTest.test_failing_branch(uint256).expected
  src/tests/integration/test-data/show/AssertTest.test_revert_branch(uint256,uint256).expected
  src/tests/integration/test-data/show/SetUpDeployTest.test_extcodesize().expected
  src/tests/integration/test_foundry_prove.py
Labels: automerge

#96 The order of notifying downstreams happens before artifacts are ready…
  .github/workflows/master-push.yml
  package/version
  pyproject.toml
  src/kontrol/__init__.py
Labels: automerge

#86 Ci/use z3 image
  .github/actions/with-docker/action.yml
  .github/workflows/Dockerfile
  .github/workflows/Dockerfile.z3
  .github/workflows/test-pr.yml
  Dockerfile
  deps/z3
  package/version
  pyproject.toml
  src/kontrol/__init__.py
Labels: automerge

#97 Remove overlooked calls to `print`
  package/version
  pyproject.toml
  src/kontrol/__init__.py
  src/kontrol/foundry.py
  src/tests/integration/test_foundry_prove.py
  src/tests/unit/test_foundry_list.py
Labels: automerge

#106 Remove unused private functions
  package/version
  pyproject.toml
  src/kontrol/__init__.py
  src/kontrol/prove.py
Labels: automerge

#99 Update dependency: deps/kevm_release
  deps/kevm_release
  flake.lock
  flake.nix
  package/version
  poetry.lock
  pyproject.toml
  src/kontrol/__init__.py
  src/kontrol/__main__.py
  src/kontrol/kompile.py
  src/tests/integration/utils.py
Labels: automerge

#113 Remove option to not simplify initial states
  package/version
  pyproject.toml
  src/kontrol/__init__.py
  src/kontrol/__main__.py
  src/kontrol/prove.py
  src/tests/integration/test-data/gas-abstraction.expected
  src/tests/integration/test-data/show/AssertTest.testFail_assert_false().expected
  src/tests/integration/test-data/show/AssertTest.testFail_assert_true().expected
  src/tests/integration/test-data/show/AssertTest.testFail_expect_revert().expected
  src/tests/integration/test-data/show/AssertTest.test_assert_false().expected
  src/tests/integration/test-data/show/AssertTest.test_assert_true().expected
  src/tests/integration/test-data/show/AssertTest.test_failing_branch(uint256).expected
  src/tests/integration/test-data/show/AssertTest.test_revert_branch(uint256,uint256).expected
  src/tests/integration/test-data/show/AssumeTest.testFail_assume_false(uint256,uint256).expected
  src/tests/integration/test-data/show/AssumeTest.testFail_assume_true(uint256,uint256).expected
  src/tests/integration/test-data/show/AssumeTest.test_assume_false(uint256,uint256).expected
  src/tests/integration/test-data/show/LoopsTest.sum_N(uint256).expected
  src/tests/integration/test-data/show/SetUpDeployTest.test_extcodesize().expected
  src/tests/integration/test_foundry_prove.py
  src/tests/profiling/test_foundry_prove.py
Labels: automerge

#111 Fix master deployments
  .github/workflows/master-push.yml
  package/version
  pyproject.toml
  src/kontrol/__init__.py
Labels: automerge

#116 Update dependency: deps/kevm_release
  deps/kevm_release
  flake.lock
  flake.nix
  package/version
  poetry.lock
  pyproject.toml
  src/kontrol/__init__.py
Labels: automerge

#108 Encapsulate program-level options
  package/version
  pyproject.toml
  src/kontrol/__init__.py
  src/kontrol/__main__.py
  src/kontrol/options.py
  src/kontrol/prove.py
  src/tests/integration/test_foundry_prove.py
  src/tests/profiling/test_foundry_prove.py
Labels: automerge

#119 Update dependency: deps/kevm_release
  deps/kevm_release
  flake.lock
  flake.nix
  package/version
  poetry.lock
  pyproject.toml
  src/kontrol/__init__.py
  src/kontrol/__main__.py
  src/kontrol/kompile.py
Labels: automerge

#109 Fix `_method_to_cfg`
  package/version
  pyproject.toml
  src/kontrol/__init__.py
  src/kontrol/prove.py
Labels: automerge

#135 Add `foundry.md`
  .github/workflows/test-pr.yml
  package/version
  pyproject.toml
  src/kontrol/__init__.py
  src/kontrol/kdist/__init__.py
  src/kontrol/kdist/foundry.md
  src/kontrol/kdist/plugin.py
  src/kontrol/kompile.py
Labels: automerge

#129 Updated documentation link in output
  package/version
  pyproject.toml
  src/kontrol/__init__.py
  src/kontrol/foundry.py
  src/tests/integration/test-data/gas-abstraction.expected
  src/tests/integration/test-data/show/AssertTest.testFail_assert_false().expected
  src/tests/integration/test-data/show/AssertTest.testFail_assert_true().expected
  src/tests/integration/test-data/show/AssertTest.testFail_expect_revert().expected
  src/tests/integration/test-data/show/AssertTest.test_assert_false().expected
  src/tests/integration/test-data/show/AssertTest.test_assert_true().expected
  src/tests/integration/test-data/show/AssertTest.test_failing_branch(uint256).expected
  src/tests/integration/test-data/show/AssertTest.test_revert_branch(uint256,uint256).expected
  src/tests/integration/test-data/show/AssumeTest.testFail_assume_false(uint256,uint256).expected
  src/tests/integration/test-data/show/AssumeTest.testFail_assume_true(uint256,uint256).expected
  src/tests/integration/test-data/show/AssumeTest.test_assume_false(uint256,uint256).expected
  src/tests/integration/test-data/show/LoopsTest.sum_N(uint256).expected
  src/tests/integration/test-data/show/SetUpDeployTest.test_extcodesize().expected
Labels: documentation

#138 Fix kup version of kontrol by building the foundryx target
  flake.nix
  package/version
  pyproject.toml
  src/kontrol/__init__.py
Labels: automerge

#145 Add escaping to sort_field
  package/version
  pyproject.toml
  src/kontrol/__init__.py
  src/kontrol/solc_to_k.py
  src/tests/integration/test-data/contracts.k.expected
Labels: automerge, bug

#103 Make test selection more similar to Foundry
  .github/workflows/test-pr.yml
  package/version
  pyproject.toml
  src/kontrol/__init__.py
  src/kontrol/__main__.py
  src/kontrol/foundry.py
  src/kontrol/prove.py
Labels: automerge, enhancement

#146 Add job to test Nix build
  .github/workflows/test-pr.yml
  package/test-package.sh
  package/test-project/foundry.toml
  package/test-project/test/Simple.t.sol
  package/version
  pyproject.toml
  src/kontrol/__init__.py
Labels: automerge

#137 Fetch `kdist.get('plugin')` for kompilation
  package/version
  pyproject.toml
  src/kontrol/__init__.py
  src/kontrol/kompile.py
Labels: automerge

#151 Update README instructions
  README.md
  package/version
  pyproject.toml
  src/kontrol/__init__.py
Labels: automerge
