Repository runtimeverification/kontrol, pull requests merged in 2023-11, with the labels that each got.

#148 Refactor prank system
  package/version
  pyproject.toml
  src/kontrol/__init__.py
  src/kontrol/kdist/foundry.md
  src/tests/integration/test-data/contracts.k.expected
  src/tests/integration/test-data/foundry.k.expected
  src/tests/integration/test-data/foundry/test/PlainPrankTest.t.sol
Labels: automerge

#152 Rename target `foundryx` to `foundry`
  .github/workflows/test-pr.yml
  README.md
  flake.nix
  package/version
  pyproject.toml
  src/kontrol/__init__.py
  src/kontrol/kdist/plugin.py
  src/kontrol/kompile.py
Labels: automerge

#155 Update dependency: deps/kevm_release
  deps/kevm_release
  flake.lock
  flake.nix
  package/version
  poetry.lock
  pyproject.toml
  src/kontrol/__init__.py
Labels: automerge

#132 Warn user if an outdated K version is being used
  package/version
  pyproject.toml
  src/kontrol/__init__.py
  src/kontrol/__main__.py
Labels: automerge, enhancement

#156 Update dependency: deps/kevm_release
  deps/kevm_release
  flake.lock
  flake.nix
  package/version
  poetry.lock
  pyproject.toml
  src/kontrol/__init__.py
  src/kontrol/prove.py
Labels: automerge

#158 Update dependency: deps/kevm_release
  deps/kevm_release
  flake.lock
  flake.nix
  package/version
  poetry.lock
  pyproject.toml
  src/kontrol/__init__.py
Labels: automerge

#161 Update dependency: deps/kevm_release
  .github/workflows/test-pr.yml
  README.md
  deps/k_release
  deps/kevm_release
  flake.lock
  flake.nix
  package/version
  poetry.lock
  pyproject.toml
  src/kontrol/__init__.py
  src/kontrol/__main__.py
  src/kontrol/kompile.py
  src/kontrol/solc_to_k.py
  src/tests/integration/utils.py
Labels: automerge

#166 Save number cell from setUp function
  package/version
  pyproject.toml
  src/kontrol/__init__.py
  src/kontrol/prove.py
  src/tests/integration/test-data/contracts.k.expected
  src/tests/integration/test-data/foundry.k.expected
  src/tests/integration/test-data/foundry/test/BlockParamsTest.t.sol
Labels: automerge, bug

#171 Reduce legacy time on CI
  package/version
  pyproject.toml
  src/kontrol/__init__.py
  src/tests/integration/test-data/foundry-prove-skip-legacy
  src/tests/integration/test_foundry_prove.py
Labels: automerge

#95 Add docs on running kore-rpc-booster on a bug report
  docs/2023-10-10-running-rpc-server-manually.md
  package/version
  pyproject.toml
  src/kontrol/__init__.py
Labels: automerge, documentation

#175 Add `.` to escaped character
  package/version
  pyproject.toml
  src/kontrol/__init__.py
  src/kontrol/solc_to_k.py
  src/tests/integration/test-data/contracts.k.expected
  src/tests/integration/test-data/foundry.k.expected
  src/tests/integration/test-data/lemmas.k
Labels: automerge

#167 Update dependency: deps/kevm_release
  deps/k_release
  deps/kevm_release
  flake.lock
  flake.nix
  package/version
  poetry.lock
  pyproject.toml
  src/kontrol/__init__.py
  src/kontrol/__main__.py
  src/kontrol/cli.py
Labels: automerge

#164 Update options: improve help for `view/show-kcfg`, refactor `smt` and `rpc_args`
  package/version
  pyproject.toml
  src/kontrol/__init__.py
  src/kontrol/__main__.py
  src/kontrol/foundry.py
  src/kontrol/options.py
  src/kontrol/prove.py
  src/tests/integration/test_foundry_prove.py
  src/tests/profiling/test_foundry_prove.py
Labels: automerge

#184 Add `--no-forge-build` option to skip `forge build`
  package/version
  pyproject.toml
  src/kontrol/__init__.py
  src/kontrol/__main__.py
  src/kontrol/kompile.py
Labels: automerge

#181 Update dependency: deps/kevm_release
  .github/workflows/test-pr.yml
  deps/k_release
  deps/kevm_release
  flake.lock
  flake.nix
  package/version
  poetry.lock
  pyproject.toml
  src/kontrol/__init__.py
  src/kontrol/kompile.py
Labels: automerge

#189 Move `--port` args to `rpc_args`
  package/version
  pyproject.toml
  src/kontrol/__init__.py
  src/kontrol/__main__.py
  src/kontrol/cli.py
Labels: automerge

#191 Update dependency: deps/kevm_release
  deps/k_release
  deps/kevm_release
  flake.lock
  flake.nix
  package/version
  poetry.lock
  pyproject.toml
  src/kontrol/__init__.py
Labels: automerge

#193 Update dependency: deps/kevm_release
  deps/k_release
  deps/kevm_release
  flake.lock
  flake.nix
  package/version
  poetry.lock
  pyproject.toml
  src/kontrol/__init__.py
Labels: automerge

#195 Update dependency: deps/kevm_release
  deps/k_release
  deps/kevm_release
  flake.lock
  flake.nix
  package/version
  poetry.lock
  pyproject.toml
  src/kontrol/__init__.py
Labels: automerge

#198 Update dependency: deps/kevm_release
  deps/k_release
  deps/kevm_release
  flake.lock
  flake.nix
  package/version
  poetry.lock
  pyproject.toml
  src/kontrol/__init__.py
Labels: automerge

#200 Add nix dev shell
  flake.nix
  package/version
  pyproject.toml
  src/kontrol/__init__.py
Labels: automerge

#201 Update dependency: deps/kevm_release
  deps/kevm_release
  flake.lock
  flake.nix
  package/version
  poetry.lock
  pyproject.toml
  src/kontrol/__init__.py
Labels: automerge

#206 Update dependency: deps/kevm_release
  deps/kevm_release
  flake.lock
  flake.nix
  package/version
  poetry.lock
  pyproject.toml
  src/kontrol/__init__.py
Labels: automerge

#179 Move expectRevert check outside of `CALL*`/`CREATE*`logic
  package/version
  pyproject.toml
  src/kontrol/__init__.py
  src/kontrol/kdist/cheatcodes.md
  src/tests/integration/test-data/contracts.k.expected
  src/tests/integration/test-data/foundry-prove-skip
  src/tests/integration/test-data/foundry/test/ExpectRevertTest.t.sol
  src/tests/integration/test-data/foundry/test/Simple.t.sol
  src/tests/integration/test-data/show/AssertTest.testFail_assert_false().expected
  src/tests/integration/test-data/show/AssertTest.testFail_assert_true().expected
  src/tests/integration/test-data/show/AssertTest.testFail_expect_revert().expected
  src/tests/integration/test-data/show/AssertTest.test_assert_false().expected
  src/tests/integration/test-data/show/AssertTest.test_assert_true().expected
  src/tests/integration/test-data/show/AssertTest.test_failing_branch(uint256).expected
  src/tests/integration/test-data/show/AssertTest.test_revert_branch(uint256,uint256).expected
Labels: automerge, enhancement

#218 Small refactor to pranks.
  package/version
  pyproject.toml
  src/kontrol/__init__.py
  src/kontrol/kdist/cheatcodes.md
Labels: automerge

#220 Add `pytest` option `foundry-root`
  package/version
  pyproject.toml
  src/kontrol/__init__.py
  src/tests/conftest.py
  src/tests/integration/test_foundry_prove.py
Labels: automerge
