Repository runtimeverification/kontrol, pull requests merged in 2023-12, with the labels that each got.

#217 Update dependency: deps/kevm_release
  .github/workflows/test-pr.yml
  Dockerfile
  README.md
  deps/k_release
  deps/kevm_release
  flake.lock
  flake.nix
  package/version
  poetry.lock
  pyproject.toml
  src/kontrol/__init__.py
  src/kontrol/__main__.py
  src/kontrol/cli.py
  src/kontrol/kompile.py
  src/kontrol/solc_to_k.py
  src/tests/integration/test-data/show/AssertTest.testFail_expect_revert().expected
Labels: automerge

#224 Various documentation fixes
  README.md
  package/version
  pyproject.toml
  src/kontrol/__init__.py
  src/kontrol/__main__.py
  src/kontrol/foundry.py
  src/kontrol/kdist/cheatcodes.md
Labels: automerge, documentation

#225 Update dependency: deps/kevm_release
  deps/k_release
  deps/kevm_release
  flake.lock
  flake.nix
  package/version
  poetry.lock
  pyproject.toml
  src/kontrol/__init__.py
Labels: automerge

#228 Simplify cheat code rules
  package/version
  pyproject.toml
  src/kontrol/__init__.py
  src/kontrol/kdist/cheatcodes.md
Labels: automerge

#229 Update dependency: deps/kevm_release
  deps/k_release
  deps/kevm_release
  flake.lock
  flake.nix
  package/version
  poetry.lock
  pyproject.toml
  src/kontrol/__init__.py
Labels: automerge

#234 Update dependency: deps/kevm_release
  deps/kevm_release
  flake.lock
  flake.nix
  package/version
  poetry.lock
  pyproject.toml
  src/kontrol/__init__.py
Labels: automerge

#235 Update dependency: deps/kevm_release
  deps/k_release
  deps/kevm_release
  flake.lock
  flake.nix
  package/version
  poetry.lock
  pyproject.toml
  src/kontrol/__init__.py
Labels: automerge

#239 Update dependency: deps/kevm_release
  deps/k_release
  deps/kevm_release
  flake.lock
  flake.nix
  package/version
  poetry.lock
  pyproject.toml
  src/kontrol/__init__.py
Labels: automerge

#236 Add solc_0_8_15 to flake
  flake.nix
  package/version
  pyproject.toml
  src/kontrol/__init__.py
Labels: automerge

#241 Update dependency: deps/kevm_release
  deps/kevm_release
  flake.lock
  flake.nix
  package/version
  poetry.lock
  pyproject.toml
  src/kontrol/__init__.py
Labels: automerge

#242 Update dependency: deps/kevm_release
  deps/k_release
  deps/kevm_release
  flake.lock
  flake.nix
  package/version
  poetry.lock
  pyproject.toml
  src/kontrol/__init__.py
Labels: automerge

#221 Deployment summaries
  package/version
  pyproject.toml
  src/kontrol/__init__.py
  src/kontrol/__main__.py
  src/kontrol/deployment.py
  src/kontrol/foundry.py
  src/tests/integration/test-data/accesses.json
  src/tests/integration/test-data/contracts.k.expected
  src/tests/integration/test-data/foundry.k.expected
  src/tests/integration/test-data/foundry/foundry.toml
  src/tests/integration/test-data/foundry/src/DeploymentSummary.sol
  src/tests/integration/test-data/foundry/src/DeploymentSummaryCode.sol
  src/tests/integration/test_foundry_prove.py
Labels: automerge, enhancement, engagement

#245 Update dependency: deps/kevm_release
  deps/k_release
  deps/kevm_release
  flake.lock
  flake.nix
  package/version
  poetry.lock
  pyproject.toml
  src/kontrol/__init__.py
Labels: automerge

#244 Fix models not being generated
  package/version
  pyproject.toml
  src/kontrol/__init__.py
  src/kontrol/prove.py
Labels: automerge, bug

#75 Make booster the default
  .github/workflows/test-pr.yml
  package/version
  pyproject.toml
  src/kontrol/__init__.py
  src/kontrol/__main__.py
  src/kontrol/cli.py
  src/tests/conftest.py
  src/tests/integration/test_foundry_prove.py
  src/tests/profiling/test_foundry_prove.py
Labels: automerge, enhancement

#250 Update dependency: deps/kevm_release
  deps/k_release
  deps/kevm_release
  flake.lock
  flake.nix
  package/version
  poetry.lock
  pyproject.toml
  src/kontrol/__init__.py
Labels: automerge

#251 Update dependency: deps/kevm_release
  deps/kevm_release
  flake.lock
  flake.nix
  package/version
  poetry.lock
  pyproject.toml
  src/kontrol/__init__.py
Labels: automerge

#219 Use absolute path to disambiguate contract names
  package/version
  pyproject.toml
  src/kontrol/__init__.py
  src/kontrol/foundry.py
  src/kontrol/kompile.py
  src/kontrol/prove.py
  src/kontrol/solc_to_k.py
  src/tests/integration/test-data/contracts.k.expected
  src/tests/integration/test-data/foundry.k.expected
  src/tests/integration/test-data/foundry/src/duplicates/1/DuplicateName.sol
  src/tests/integration/test-data/foundry/src/duplicates/2/DuplicateName.sol
  src/tests/integration/test-data/lemmas.k
  src/tests/integration/test_foundry_prove.py
  src/tests/unit/test_foundry_list.py
Labels: automerge, bug, engagement

#253 Update dependency: deps/kevm_release
  deps/k_release
  deps/kevm_release
  flake.lock
  flake.nix
  package/version
  poetry.lock
  pyproject.toml
  src/kontrol/__init__.py
  src/kontrol/prove.py
  src/tests/integration/test-data/gas-abstraction.expected
  src/tests/integration/test-data/show/AssertTest.testFail_assert_false().expected
  src/tests/integration/test-data/show/AssertTest.testFail_assert_true().expected
  src/tests/integration/test-data/show/AssertTest.testFail_expect_revert().expected
  src/tests/integration/test-data/show/AssertTest.test_assert_false().expected
  src/tests/integration/test-data/show/AssertTest.test_assert_true().expected
  src/tests/integration/test-data/show/AssertTest.test_failing_branch(uint256).expected
  src/tests/integration/test-data/show/AssertTest.test_revert_branch(uint256,uint256).expected
  src/tests/integration/test-data/show/AssumeTest.testFail_assume_false(uint256,uint256).expected
  src/tests/integration/test-data/show/AssumeTest.test_assume_false(uint256,uint256).expected
Labels: automerge
