Repository runtimeverification/kontrol, pull requests merged in 2024-12, with the labels that each got.

#900 Add a rule removing init code size limit checks
  src/kontrol/kdist/no_code_size_checks.md
Labels: automerge, engagement

#903 Update dependency: deps/kevm_release
  deps/k_release
  deps/kevm_release
  flake.lock
  flake.nix
  poetry.lock
  pyproject.toml
Labels: automerge

#904 Update dependency: deps/kevm_release
  deps/kevm_release
  flake.lock
  flake.nix
  poetry.lock
  pyproject.toml
Labels: automerge

#907 Turn on `O2` by default, add it to `kontrol.toml`
  src/kontrol/cli.py
  src/kontrol/options.py
  src/kontrol/utils.py
Labels: automerge

#902 Add cheatcodes that generate symbolic variables with custom names
  src/kontrol/foundry.py
  src/kontrol/kdist/cheatcodes.md
  src/kontrol/prove.py
  src/kontrol/utils.py
  src/tests/integration/test-data/end-to-end-prove-all
  src/tests/integration/test-data/end-to-end-prove-show
  src/tests/integration/test-data/show/RandomVarTest.test_custom_names().expected
  src/tests/integration/test-data/src/RandomVar.t.sol
  src/tests/integration/test_kontrol.py
  src/tests/unit/test_foundry_prove.py
Labels: automerge

#910 Stop appending the storageLayout extra output to foundry.toml
  src/kontrol/foundry.py
  src/kontrol/utils.py
Labels: automerge

#913 Enable publishing a Docker image from a branch
  .github/workflows/docker-push.yml
Labels: automerge

#915 Fix nested struct array rule generation
  src/kontrol/solc_to_k.py
  src/tests/integration/test-data/foundry/test/NestedArrayStructs.t.sol
  src/tests/integration/test-data/show/contracts.k.expected
  src/tests/integration/test-data/show/foundry.k.expected
Labels: automerge, bug, engagement

#916 Set `processed_link_refs` to `true` only in `setup` or constructor
  src/kontrol/prove.py
  src/tests/integration/test-data/foundry-prove-all
  src/tests/integration/test-data/foundry-prove-skip-legacy
  src/tests/integration/test-data/foundry/test/ExternalLibTest.t.sol
  src/tests/integration/test-data/show/contracts.k.expected
Labels: automerge

#911 Update dependency: deps/kevm_release
  deps/k_release
  deps/kevm_release
  flake.lock
  flake.nix
  poetry.lock
  pyproject.toml
Labels: automerge

#917 Update dependency: deps/kevm_release
  deps/k_release
  deps/kevm_release
  flake.lock
  flake.nix
  poetry.lock
  pyproject.toml
Labels: automerge

#918 Update dependency: deps/kevm_release
  deps/kevm_release
  flake.lock
  flake.nix
  poetry.lock
  pyproject.toml
  src/kontrol/prove.py
Labels: automerge

#920 Update dependency: deps/kevm_release
  deps/k_release
  deps/kevm_release
  flake.lock
  flake.nix
  poetry.lock
  pyproject.toml
Labels: automerge

#921 Add from_option_string to RPCOptions
  src/kontrol/options.py
Labels: automerge, bug
