Repository runtimeverification/kontrol, pull requests merged in 2024-01, with the labels that each got.

#252 Disable gas computations in Kontrol
  package/version
  pyproject.toml
  src/kontrol/__init__.py
  src/kontrol/__main__.py
  src/kontrol/options.py
  src/kontrol/prove.py
  src/tests/integration/test-data/foundry-prove-with-gas
  src/tests/integration/test-data/show/AssertTest.testFail_assert_false().expected
  src/tests/integration/test-data/show/AssertTest.testFail_assert_true().expected
  src/tests/integration/test-data/show/AssertTest.testFail_expect_revert().expected
  src/tests/integration/test-data/show/AssertTest.test_assert_false().expected
  src/tests/integration/test-data/show/AssertTest.test_assert_true().expected
  src/tests/integration/test-data/show/AssertTest.test_failing_branch(uint256).expected
  src/tests/integration/test-data/show/AssertTest.test_revert_branch(uint256,uint256).expected
  src/tests/integration/test-data/show/AssumeTest.testFail_assume_false(uint256,uint256).expected
  src/tests/integration/test-data/show/AssumeTest.test_assume_false(uint256,uint256).expected
  src/tests/integration/test_foundry_prove.py
Labels: automerge, enhancement

#258 Update dependency: deps/kevm_release
  deps/kevm_release
  flake.lock
  flake.nix
  package/version
  poetry.lock
  pyproject.toml
  src/kontrol/__init__.py
  src/kontrol/__main__.py
  src/kontrol/options.py
  src/kontrol/prove.py
  src/tests/integration/test-data/gas-abstraction.expected
  src/tests/integration/test-data/show/AssertTest.testFail_expect_revert().expected
  src/tests/integration/test-data/show/AssumeTest.testFail_assume_false(uint256,uint256).expected
  src/tests/integration/test-data/show/AssumeTest.test_assume_false(uint256,uint256).expected
Labels: automerge

#267 Update dependency: deps/kevm_release
  deps/kevm_release
  flake.lock
  flake.nix
  package/version
  poetry.lock
  pyproject.toml
  src/kontrol/__init__.py
Labels: automerge

#261 Enable breaking on all foundry actions
  package/version
  pyproject.toml
  src/kontrol/__init__.py
  src/kontrol/__main__.py
  src/kontrol/kdist/cheatcodes.md
  src/kontrol/options.py
  src/kontrol/prove.py
Labels: automerge

#227 Write `KompiledKore` data structures on `foundry_kompile`
  package/version
  pyproject.toml
  src/kontrol/__init__.py
  src/kontrol/kompile.py
Labels: automerge

#268 Update dependency: deps/kevm_release
  deps/k_release
  deps/kevm_release
  flake.lock
  flake.nix
  package/version
  poetry.lock
  pyproject.toml
  src/kontrol/__init__.py
  src/tests/integration/test-data/show/AssertTest.testFail_expect_revert().expected
Labels: automerge

#249 Verify `proveX` and `checkX` functions similarly to `testX`
  package/version
  pyproject.toml
  src/kontrol/__init__.py
  src/kontrol/prove.py
  src/tests/integration/test-data/contracts.k.expected
  src/tests/integration/test-data/foundry-prove-all
  src/tests/integration/test-data/foundry-prove-skip-legacy
  src/tests/integration/test-data/foundry-show
  src/tests/integration/test-data/foundry/test/Simple.t.sol
  src/tests/integration/test-data/show/AssertTest.checkFail_assert_false().expected
  src/tests/integration/test-data/show/AssertTest.testFail_assert_true().expected
  src/tests/integration/test-data/show/AssertTest.testFail_expect_revert().expected
  src/tests/integration/test-data/show/AssertTest.test_assert_false().expected
  src/tests/integration/test-data/show/AssertTest.test_assert_true().expected
  src/tests/integration/test-data/show/AssertTest.test_failing_branch(uint256).expected
  src/tests/integration/test-data/show/AssertTest.test_revert_branch(uint256,uint256).expected
Labels: automerge

#273 Update dependency: deps/kevm_release
  deps/kevm_release
  flake.lock
  flake.nix
  package/version
  poetry.lock
  pyproject.toml
  src/kontrol/__init__.py
Labels: automerge

#274 Update foundry.nix
  package/version
  pyproject.toml
  src/kontrol/__init__.py
Labels: automerge

#263 Added comment to kontrol summary auto-generated file
  package/version
  pyproject.toml
  src/kontrol/__init__.py
  src/kontrol/__main__.py
  src/kontrol/deployment.py
  src/kontrol/foundry.py
  src/tests/integration/test-data/contracts.k.expected
  src/tests/integration/test-data/foundry/src/DeploymentSummary.sol
  src/tests/integration/test-data/foundry/src/DeploymentSummaryCode.sol
  src/tests/integration/test_foundry_prove.py
Labels: automerge

#277 Update dependency: deps/kevm_release
  deps/kevm_release
  flake.lock
  flake.nix
  package/version
  poetry.lock
  pyproject.toml
  src/kontrol/__init__.py
Labels: automerge

#271 Implement fast summarization
  package/version
  pyproject.toml
  src/kontrol/__init__.py
  src/kontrol/__main__.py
  src/kontrol/deployment.py
  src/kontrol/foundry.py
  src/kontrol/options.py
  src/kontrol/prove.py
  src/kontrol/solc_to_k.py
  src/tests/unit/test-data/accesses.json
  src/tests/unit/test_foundry_prove.py
Labels: automerge, enhancement, engagement

#280 Update dependency: deps/kevm_release
  deps/kevm_release
  flake.lock
  flake.nix
  package/version
  poetry.lock
  pyproject.toml
  src/kontrol/__init__.py
Labels: automerge

#289 Avoid using the same priority for rules that apply on the same KItem
  package/version
  pyproject.toml
  src/kontrol/__init__.py
  src/kontrol/kdist/cheatcodes.md
  src/tests/integration/test-data/contracts.k.expected
  src/tests/integration/test-data/foundry-prove-all
  src/tests/integration/test-data/foundry/test/PlainPrankTest.t.sol
Labels: automerge, bug

#287 Set up cells
  package/version
  pyproject.toml
  src/kontrol/__init__.py
  src/kontrol/prove.py
  src/tests/integration/test-data/contracts.k.expected
  src/tests/integration/test-data/foundry-prove-all
  src/tests/integration/test-data/foundry.k.expected
  src/tests/integration/test-data/foundry/src/Prank.sol
  src/tests/integration/test-data/foundry/test/BlockParamsTest.t.sol
  src/tests/integration/test-data/foundry/test/PrankTest.t.sol
Labels: bug

#297 Change visibility of `vm` in deployment summary to private
  package/version
  pyproject.toml
  src/kontrol/__init__.py
  src/kontrol/deployment.py
  src/tests/integration/test-data/contracts.k.expected
  src/tests/integration/test-data/foundry/src/DeploymentSummary.sol
Labels: automerge

#302 Update dependency: deps/kevm_release
  deps/k_release
  deps/kevm_release
  flake.lock
  flake.nix
  package/version
  poetry.lock
  pyproject.toml
  src/kontrol/__init__.py
Labels: automerge

#306 Fix pickling issue on deep proof objects
  package/version
  pyproject.toml
  src/kontrol/__init__.py
  src/kontrol/prove.py
Labels: automerge

#307 Update dependency: deps/kevm_release
  deps/k_release
  deps/kevm_release
  flake.lock
  flake.nix
  package/version
  poetry.lock
  pyproject.toml
  src/kontrol/__init__.py
Labels: automerge

#310 Update dependency: deps/kevm_release
  deps/kevm_release
  flake.lock
  flake.nix
  package/version
  poetry.lock
  pyproject.toml
  src/kontrol/__init__.py
Labels: automerge

#309 Display rule logs in custom view
  package/version
  pyproject.toml
  src/kontrol/__init__.py
  src/kontrol/foundry.py
Labels: automerge

#294 Publish Kontrol to Cachix binary cache
  .github/workflows/master-push.yml
  package/version
  pyproject.toml
  src/kontrol/__init__.py
Labels: automerge

#308 Improvements to proof-loading speed on reruns
  .flake8
  .gitignore
  package/version
  pyproject.toml
  src/kontrol/__init__.py
  src/kontrol/foundry.py
  src/kontrol/prove.py
  src/tests/integration/test_foundry_prove.py
Labels: automerge

#264 Refactor init and final terms for symbolic exploration
  package/version
  pyproject.toml
  src/kontrol/__init__.py
  src/kontrol/foundry.py
  src/kontrol/kdist/cheatcodes.md
  src/kontrol/prove.py
  src/tests/integration/test-data/gas-abstraction.expected
  src/tests/integration/test-data/show/AssertTest.checkFail_assert_false().expected
  src/tests/integration/test-data/show/AssertTest.testFail_assert_true().expected
  src/tests/integration/test-data/show/AssertTest.testFail_expect_revert().expected
  src/tests/integration/test-data/show/AssertTest.test_assert_false().expected
  src/tests/integration/test-data/show/AssertTest.test_assert_true().expected
  src/tests/integration/test-data/show/AssertTest.test_failing_branch(uint256).expected
  src/tests/integration/test-data/show/AssertTest.test_revert_branch(uint256,uint256).expected
  src/tests/integration/test-data/show/AssumeTest.testFail_assume_false(uint256,uint256).expected
  src/tests/integration/test-data/show/AssumeTest.test_assume_false(uint256,uint256).expected
Labels: enhancement

#311 Update dependency: deps/kevm_release
  deps/k_release
  deps/kevm_release
  flake.lock
  flake.nix
  package/version
  poetry.lock
  pyproject.toml
  src/kontrol/__init__.py
  src/kontrol/kdist/cheatcodes.md
  src/tests/integration/test-data/show/AssertTest.testFail_expect_revert().expected
  src/tests/integration/test_foundry_prove.py
Labels: automerge

#314 Update dependency: deps/kevm_release
  deps/k_release
  deps/kevm_release
  flake.lock
  flake.nix
  package/version
  poetry.lock
  pyproject.toml
  src/kontrol/__init__.py
Labels: automerge

#323 Update dependency: deps/kevm_release
  deps/kevm_release
  flake.lock
  flake.nix
  package/version
  poetry.lock
  pyproject.toml
  src/kontrol/__init__.py
Labels: automerge
