Repository runtimeverification/kontrol, pull requests merged in 2024-10, with the labels that each got.

#842 Optimization flags for kontrol build
  .github/workflows/test-pr.yml
  src/kontrol/kompile.py
Labels: automerge

#843 Update dependency: deps/kevm_release
  deps/kevm_release
  flake.lock
  flake.nix
  poetry.lock
  pyproject.toml
Labels: automerge

#846 Preserve `bounded` nodes from `setUp` in `test`
  src/kontrol/prove.py
  src/tests/integration/test-data/foundry-bmc-all
  src/tests/integration/test-data/foundry-show
  src/tests/integration/test-data/foundry/test/BMCBound.t.sol
  src/tests/integration/test-data/show/BMCBoundTest.testBound().expected
  src/tests/integration/test-data/show/contracts.k.expected
  src/tests/integration/test-data/show/foundry.k.expected
  src/tests/integration/test_foundry_prove.py
Labels: bug

#838 Add support for external libraries
  src/kontrol/prove.py
  src/kontrol/solc.py
  src/kontrol/solc_to_k.py
  src/kontrol/utils.py
  src/tests/integration/test-data/foundry-prove-all
  src/tests/integration/test-data/foundry-prove-skip-legacy
  src/tests/integration/test-data/foundry/test/ExternalLibTest.t.sol
  src/tests/integration/test-data/show/contracts.k.expected
  src/tests/integration/test-data/show/foundry.k.expected
Labels: automerge, enhancement

#847 Update dependency: deps/kevm_release
  deps/k_release
  deps/kevm_release
  flake.lock
  flake.nix
  poetry.lock
  pyproject.toml
Labels: automerge

#848 Simplifying nodes by need
  flake.lock
  src/kontrol/prove.py
  src/tests/integration/test-data/show/AssertTest.checkFail_assert_false().expected
  src/tests/integration/test-data/show/AssertTest.testFail_assert_true().expected
  src/tests/integration/test-data/show/AssertTest.testFail_expect_revert().expected
  src/tests/integration/test-data/show/AssertTest.test_assert_false().expected
  src/tests/integration/test-data/show/AssertTest.test_assert_true().expected
  src/tests/integration/test-data/show/AssertTest.test_failing_branch(uint256).expected
  src/tests/integration/test-data/show/AssertTest.test_revert_branch(uint256,uint256).expected
  src/tests/integration/test-data/show/BMCBoundTest.testBound().expected
  src/tests/integration/test-data/show/SetUpDeployTest.test_extcodesize().expected
  src/tests/integration/test-data/show/split-node.expected
Labels: enhancement

#849 Update dependency: deps/kevm_release
  deps/kevm_release
  flake.lock
  flake.nix
  poetry.lock
  pyproject.toml
Labels: automerge

#854 Update dependency: deps/kevm_release
  deps/k_release
  deps/kevm_release
  flake.lock
  flake.nix
  poetry.lock
  pyproject.toml
  src/tests/integration/test-data/show/ArithmeticCallTest.test_double_add(uint256,uint256).cse.expected
  src/tests/integration/test-data/show/ArithmeticCallTest.test_double_add_double_sub(uint256,uint256).cse.expected
  src/tests/integration/test-data/show/ArithmeticCallTest.test_double_add_sub_external(uint256,uint256,uint256).cse.expected
  src/tests/integration/test-data/show/ArithmeticContract.add_sub_external(uint256,uint256,uint256).cse.expected
  src/tests/integration/test-data/show/TGovernance.getEscrowTokenTotalSupply().cse.expected
  src/tests/integration/test-data/show/merge-loop-heads.expected
Labels: automerge

#855 Fix `Option` printing
  src/kontrol/options.py
Labels: automerge

#859 Add `setUp` and `init` to XML report
  src/kontrol/foundry.py
  src/kontrol/prove.py
Labels: automerge, enhancement, engagement

#857 Update dependency: deps/kevm_release
  deps/k_release
  deps/kevm_release
  flake.lock
  flake.nix
  poetry.lock
  pyproject.toml
  src/kontrol/kdist/kontrol_lemmas.md
Labels: automerge

#862 Update dependency: deps/kevm_release
  deps/k_release
  deps/kevm_release
  flake.lock
  flake.nix
  poetry.lock
  pyproject.toml
Labels: automerge

#864 Update dependency: deps/kevm_release
  deps/k_release
  deps/kevm_release
  flake.lock
  flake.nix
  poetry.lock
  pyproject.toml
Labels: automerge

#865 Update dependency: deps/kevm_release
  deps/kevm_release
  flake.lock
  flake.nix
  poetry.lock
  pyproject.toml
  src/kontrol/solc_to_k.py
Labels: automerge

#868 Update dependency: deps/kevm_release
  deps/k_release
  deps/kevm_release
  flake.lock
  flake.nix
  poetry.lock
  pyproject.toml
Labels: automerge

#870 Add section `Selectors` to `cheatcodes.md`
  src/kontrol/kdist/cheatcodes.md
Labels: automerge

#872 Update dependency: deps/kevm_release
  deps/kevm_release
  flake.lock
  flake.nix
  poetry.lock
  pyproject.toml
Labels: automerge

#874 Update dependency: deps/kevm_release
  deps/k_release
  deps/kevm_release
  flake.lock
  flake.nix
  poetry.lock
  pyproject.toml
Labels: automerge
