Repository runtimeverification/kontrol, pull requests merged in 2024-02, with the labels that each got.

#313 Refactor production of initial terms, factor out method identification
  package/version
  poetry.lock
  pyproject.toml
  src/kontrol/__init__.py
  src/kontrol/foundry.py
  src/kontrol/prove.py
  src/kontrol/solc_to_k.py
  src/tests/integration/test-data/gas-abstraction.expected
  src/tests/integration/test-data/show/AssertTest.checkFail_assert_false().expected
  src/tests/integration/test-data/show/AssertTest.testFail_assert_true().expected
  src/tests/integration/test-data/show/AssertTest.testFail_expect_revert().expected
  src/tests/integration/test-data/show/AssertTest.test_assert_false().expected
  src/tests/integration/test-data/show/AssertTest.test_assert_true().expected
  src/tests/integration/test-data/show/AssertTest.test_failing_branch(uint256).expected
  src/tests/integration/test-data/show/AssertTest.test_revert_branch(uint256,uint256).expected
  src/tests/integration/test-data/show/AssumeTest.testFail_assume_false(uint256,uint256).expected
  src/tests/integration/test-data/show/AssumeTest.test_assume_false(uint256,uint256).expected
Labels: automerge

#320 Add support for NatSpec comments in proofs
  package/test-project/foundry.toml
  package/version
  pyproject.toml
  src/kontrol/__init__.py
  src/kontrol/solc_to_k.py
  src/tests/integration/test-data/contracts.k.expected
  src/tests/unit/test_solc_to_k.py
Labels: enhancement, engagement

#327 Give pytest an upper bound <8.0.0
  package/version
  poetry.lock
  pyproject.toml
  src/kontrol/__init__.py
Labels: automerge

#326 Fetch the correct proof id in case of nested dir structure
  package/version
  pyproject.toml
  src/kontrol/__init__.py
  src/kontrol/foundry.py
  src/tests/unit/test_foundry_list.py
Labels: automerge, bug

#330 Stabalize output of prover
  .github/workflows/test-pr.yml
  package/version
  pyproject.toml
  src/kontrol/__init__.py
  src/kontrol/foundry.py
  src/tests/integration/test-data/contracts.k.expected
  src/tests/integration/test-data/foundry/src/DeploymentSummary.sol
  src/tests/integration/test-data/foundry/src/DeploymentSummaryCode.sol
  src/tests/integration/test-data/gas-abstraction.expected
  src/tests/integration/test-data/show/AssertTest.checkFail_assert_false().expected
  src/tests/integration/test-data/show/AssertTest.testFail_assert_true().expected
  src/tests/integration/test-data/show/AssertTest.testFail_expect_revert().expected
  src/tests/integration/test-data/show/AssertTest.test_assert_false().expected
  src/tests/integration/test-data/show/AssertTest.test_assert_true().expected
  src/tests/integration/test-data/show/AssertTest.test_failing_branch(uint256).expected
  src/tests/integration/test-data/show/AssertTest.test_revert_branch(uint256,uint256).expected
  src/tests/integration/test-data/show/AssumeTest.testFail_assume_false(uint256,uint256).expected
  src/tests/integration/test-data/show/AssumeTest.test_assume_false(uint256,uint256).expected
  src/tests/integration/test_foundry_prove.py
Labels: automerge

#325 Update dependency: deps/kevm_release
  deps/k_release
  deps/kevm_release
  flake.lock
  flake.nix
  package/version
  poetry.lock
  pyproject.toml
  src/kontrol/__init__.py
  src/tests/integration/test-data/gas-abstraction.expected
  src/tests/integration/test-data/show/AssertTest.checkFail_assert_false().expected
  src/tests/integration/test-data/show/AssertTest.testFail_assert_true().expected
  src/tests/integration/test-data/show/AssertTest.testFail_expect_revert().expected
  src/tests/integration/test-data/show/AssertTest.test_assert_false().expected
  src/tests/integration/test-data/show/AssertTest.test_assert_true().expected
  src/tests/integration/test-data/show/AssertTest.test_failing_branch(uint256).expected
  src/tests/integration/test-data/show/AssertTest.test_revert_branch(uint256,uint256).expected
  src/tests/integration/test-data/show/AssumeTest.testFail_assume_false(uint256,uint256).expected
  src/tests/integration/test-data/show/AssumeTest.test_assume_false(uint256,uint256).expected
Labels: automerge

#284 Initial manual implementation of CSE
  package/version
  pyproject.toml
  src/kontrol/__init__.py
  src/kontrol/__main__.py
  src/kontrol/prove.py
  src/tests/integration/test-data/contracts.k.expected
  src/tests/integration/test-data/foundry-prove-all
  src/tests/integration/test-data/foundry-prove-skip
  src/tests/integration/test-data/foundry-prove-skip-legacy
  src/tests/integration/test-data/foundry.k.expected
  src/tests/integration/test-data/foundry/src/ArithmeticContract.sol
  src/tests/integration/test-data/foundry/test/ArithmeticCall.t.sol
  src/tests/integration/test-data/show/ArithmeticCallTest.test_double_add(uint256,uint256).expected
  src/tests/integration/test_foundry_prove.py
Labels: automerge, enhancement

#342 Migrate tests over to booster backend, minimize legacy backend time
  .github/workflows/test-pr.yml
  package/version
  pyproject.toml
  src/kontrol/__init__.py
  src/tests/integration/test-data/foundry-prove-skip-legacy
  src/tests/integration/test-data/foundry-show
  src/tests/integration/test-data/show/AssertTest.test_failing_branch(uint256).expected
  src/tests/integration/test-data/show/AssertTest.test_revert_branch(uint256,uint256).expected
  src/tests/integration/test-data/show/AssumeTest.testFail_assume_true(uint256,uint256).expected
  src/tests/integration/test-data/show/AssumeTest.test_assume_false(uint256,uint256).expected
  src/tests/integration/test-data/show/LoopsTest.sum_N(uint256).expected
  src/tests/integration/test-data/show/SetUpDeployTest.test_extcodesize().expected
  src/tests/integration/test-data/show/contracts.k.expected
  src/tests/integration/test-data/show/foundry.k.expected
  src/tests/integration/test-data/show/gas-abstraction.expected
  src/tests/integration/test_foundry_prove.py
Labels: automerge

#336 Add license file
  LICENSE
  package/version
  pyproject.toml
  src/kontrol/__init__.py
Labels: automerge, enhancement

#339 Avoid pranking on cheat codes
  package/version
  pyproject.toml
  src/kontrol/__init__.py
  src/kontrol/kdist/cheatcodes.md
  src/tests/integration/test-data/foundry/test/PlainPrankTest.t.sol
  src/tests/integration/test-data/show/contracts.k.expected
Labels: automerge, bug, engagement

#341 Update dependency: deps/kevm_release
  deps/k_release
  deps/kevm_release
  flake.lock
  flake.nix
  package/version
  poetry.lock
  pyproject.toml
  src/kontrol/__init__.py
Labels: automerge

#343 Update dependency: deps/kevm_release
  deps/kevm_release
  flake.lock
  flake.nix
  package/version
  poetry.lock
  pyproject.toml
  src/kontrol/__init__.py
Labels: automerge

#346 Update dependency: deps/kevm_release
  deps/kevm_release
  flake.lock
  flake.nix
  package/version
  poetry.lock
  pyproject.toml
  src/kontrol/__init__.py
Labels: automerge

#317 Added project root relative path as method label prefixes
  package/version
  pyproject.toml
  src/kontrol/__init__.py
  src/kontrol/solc_to_k.py
  src/tests/integration/test-data/foundry/src/duplicates/1/DuplicateName.sol
  src/tests/integration/test-data/foundry/src/duplicates/2/DuplicateName.sol
  src/tests/integration/test-data/show/contracts.k.expected
Labels: enhancement

#318 Implementation of `mockCall` cheat code
  package/version
  pyproject.toml
  src/kontrol/__init__.py
  src/kontrol/kdist/cheatcodes.md
  src/kontrol/prove.py
  src/tests/integration/test-data/foundry-prove-all
  src/tests/integration/test-data/foundry-prove-skip
  src/tests/integration/test-data/foundry-prove-skip-legacy
  src/tests/integration/test-data/foundry/src/Mock.sol
  src/tests/integration/test-data/foundry/test/MockCallTest.t.sol
  src/tests/integration/test-data/show/AssertTest.checkFail_assert_false().expected
  src/tests/integration/test-data/show/AssertTest.testFail_assert_true().expected
  src/tests/integration/test-data/show/AssertTest.testFail_expect_revert().expected
  src/tests/integration/test-data/show/AssertTest.test_assert_false().expected
  src/tests/integration/test-data/show/AssertTest.test_assert_true().expected
  src/tests/integration/test-data/show/AssertTest.test_failing_branch(uint256).expected
  src/tests/integration/test-data/show/AssertTest.test_revert_branch(uint256,uint256).expected
  src/tests/integration/test-data/show/AssumeTest.testFail_assume_false(uint256,uint256).expected
  src/tests/integration/test-data/show/AssumeTest.testFail_assume_true(uint256,uint256).expected
  src/tests/integration/test-data/show/AssumeTest.test_assume_false(uint256,uint256).expected
  src/tests/integration/test-data/show/SetUpDeployTest.test_extcodesize().expected
  src/tests/integration/test-data/show/contracts.k.expected
  src/tests/integration/test-data/show/foundry.k.expected
  src/tests/integration/test-data/show/gas-abstraction.expected
Labels: automerge, enhancement, engagement

#351 Skip tests that take more than 300s in legacy backend
  package/version
  pyproject.toml
  src/kontrol/__init__.py
  src/tests/integration/test-data/foundry-prove-skip-legacy
Labels: automerge

#352 `make test-integration` generates `bug_report` with the definition files
  package/version
  pyproject.toml
  src/kontrol/__init__.py
  src/tests/integration/test_foundry_prove.py
Labels: automerge

#348 Update dependency: deps/kevm_release
  deps/kevm_release
  flake.lock
  flake.nix
  package/version
  poetry.lock
  pyproject.toml
  src/kontrol/__init__.py
Labels: automerge

#321 Add support for dynamic types
  package/version
  pyproject.toml
  src/kontrol/__init__.py
  src/kontrol/prove.py
  src/kontrol/solc_to_k.py
  src/tests/integration/test-data/foundry-prove-all
  src/tests/integration/test-data/foundry-prove-skip
  src/tests/integration/test-data/foundry-prove-skip-legacy
  src/tests/integration/test-data/foundry/foundry.toml
  src/tests/integration/test-data/foundry/test/DynamicTypes.t.sol
  src/tests/integration/test-data/show/contracts.k.expected
  src/tests/integration/test-data/show/foundry.k.expected
  src/tests/unit/test_solc_to_k.py
Labels: automerge, enhancement, engagement

#364 Update dependency: deps/kevm_release
  deps/kevm_release
  flake.lock
  flake.nix
  package/version
  poetry.lock
  pyproject.toml
  src/kontrol/__init__.py
Labels: automerge

#349 Fix fail_fast option not getting passed to run_prover
  package/version
  pyproject.toml
  src/kontrol/__init__.py
  src/kontrol/prove.py
  src/tests/integration/test-data/show/AssertTest.test_revert_branch(uint256,uint256).expected
  src/tests/integration/test_foundry_prove.py
Labels: automerge, bug

#365 Update dependency: deps/kevm_release
  deps/kevm_release
  flake.lock
  flake.nix
  package/version
  poetry.lock
  pyproject.toml
  src/kontrol/__init__.py
Labels: automerge

#367 Update dependency: deps/kevm_release
  deps/kevm_release
  flake.lock
  flake.nix
  package/version
  poetry.lock
  pyproject.toml
  src/kontrol/__init__.py
  src/kontrol/foundry.py
  src/kontrol/prove.py
  src/tests/unit/test-data/foundry-list/apr_proofs/test%AssertTest.checkFail_assert_false():0/proof.json
  src/tests/unit/test-data/foundry-list/apr_proofs/test%AssertTest.setUp():0/proof.json
  src/tests/unit/test-data/foundry-list/apr_proofs/test%AssertTest.testFail_assert_true():0/proof.json
  src/tests/unit/test-data/foundry-list/apr_proofs/test%AssertTest.test_assert_false():0/proof.json
  src/tests/unit/test-data/foundry-list/apr_proofs/test%AssertTest.test_assert_true():0/proof.json
  src/tests/unit/test-data/foundry-list/foundry-list.expected
Labels: automerge

#368 Update dependency: deps/kevm_release
  deps/kevm_release
  flake.lock
  flake.nix
  package/version
  poetry.lock
  pyproject.toml
  src/kontrol/__init__.py
  src/kontrol/prove.py
Labels: automerge

#370 Update dependency: deps/kevm_release
  deps/kevm_release
  flake.lock
  flake.nix
  package/version
  poetry.lock
  pyproject.toml
  src/kontrol/__init__.py
Labels: automerge

#376 Update dependency: deps/kevm_release
  deps/kevm_release
  flake.lock
  flake.nix
  package/version
  poetry.lock
  pyproject.toml
  src/kontrol/__init__.py
Labels: automerge

#378 Update dependency: deps/kevm_release
  deps/kevm_release
  flake.lock
  flake.nix
  package/version
  poetry.lock
  pyproject.toml
  src/kontrol/__init__.py
Labels: automerge

#387 Update dependency: deps/kevm_release
  deps/kevm_release
  flake.lock
  flake.nix
  package/version
  poetry.lock
  pyproject.toml
  src/kontrol/__init__.py
Labels: automerge

#388 Update dependency: deps/kevm_release
  deps/kevm_release
  flake.lock
  flake.nix
  package/version
  poetry.lock
  pyproject.toml
  src/kontrol/__init__.py
Labels: automerge

#390 Update dependency: deps/kevm_release
  deps/kevm_release
  flake.lock
  flake.nix
  package/version
  poetry.lock
  pyproject.toml
  src/kontrol/__init__.py
Labels: automerge

#254 Add symbolic bytes cheatcode
  package/version
  poetry.lock
  pyproject.toml
  src/kontrol/__init__.py
  src/kontrol/foundry.py
  src/kontrol/kdist/cheatcodes.md
  src/tests/integration/test-data/foundry-prove-all
  src/tests/integration/test-data/foundry-prove-skip-legacy
  src/tests/integration/test-data/foundry/src/KEVMCheats.sol
  src/tests/integration/test-data/foundry/test/FreshBytes.t.sol
  src/tests/integration/test-data/show/contracts.k.expected
  src/tests/integration/test-data/show/foundry.k.expected
Labels: enhancement

#381 Add `kontrol refute-node` and `kontrol unrefute-node` commands
  package/version
  pyproject.toml
  src/kontrol/__init__.py
  src/kontrol/__main__.py
  src/kontrol/foundry.py
  src/tests/integration/test-data/show/node-refutation.expected
  src/tests/integration/test_foundry_prove.py
Labels: automerge

#393 Update dependency: deps/kevm_release
  deps/kevm_release
  flake.lock
  flake.nix
  package/version
  poetry.lock
  pyproject.toml
  src/kontrol/__init__.py
Labels: automerge

#399 [Hotfix] Add support for latest foundry version
  package/version
  pyproject.toml
  src/kontrol/__init__.py
  src/kontrol/solc_to_k.py
  src/tests/integration/test-data/foundry/foundry.toml
Labels: automerge, bug

#398 Allow non-general init state for non-test functions
  package/version
  pyproject.toml
  src/kontrol/__init__.py
  src/kontrol/__main__.py
  src/kontrol/options.py
  src/kontrol/prove.py
Labels: automerge, enhancement

#397 Replace `.` by `.K` in K source files
  package/version
  pyproject.toml
  src/kontrol/__init__.py
  src/kontrol/kdist/cheatcodes.md
Labels: automerge

#286 Annotating rules that preserve definedness
  package/version
  pyproject.toml
  src/kontrol/__init__.py
  src/kontrol/kdist/cheatcodes.md
Labels: automerge
