Repository runtimeverification/kontrol, pull requests merged in 2024-07, with the labels that each got.

#660 Add check for storageLayout
  package/version
  pyproject.toml
  src/kontrol/__init__.py
  src/kontrol/prove.py
  src/kontrol/solc_to_k.py
Labels: automerge

#659 Update dependency: deps/kevm_release
  deps/k_release
  deps/kevm_release
  flake.lock
  flake.nix
  package/version
  poetry.lock
  pyproject.toml
  src/kontrol/__init__.py
  src/kontrol/prove.py
Labels: automerge

#657 Enable external computation via `vm.dumpState`
  docs/external-computation/README.md
  docs/external-computation/test/kontrol/proofs/utils/InitialState.sol
  docs/external-computation/test/kontrol/proofs/utils/InitialStateCode.sol
  docs/external-computation/test/kontrol/scripts/record-state-diff.sh
  package/version
  poetry.lock
  pyproject.toml
  src/kontrol/__init__.py
  src/kontrol/__main__.py
  src/kontrol/cli.py
  src/kontrol/foundry.py
  src/kontrol/options.py
  src/kontrol/prove.py
  src/kontrol/state_record.py
  src/tests/integration/test-data/dumpState.json
  src/tests/integration/test-data/foundry/src/ContractToRecordState.sol
  src/tests/integration/test-data/foundry/src/LoadStateDiff.sol
  src/tests/integration/test-data/foundry/src/LoadStateDiffCode.sol
  src/tests/integration/test-data/foundry/src/LoadStateDump.sol
  src/tests/integration/test-data/foundry/src/LoadStateDumpCode.sol
  src/tests/integration/test-data/show/contracts.k.expected
  src/tests/integration/test-data/show/foundry.k.expected
  src/tests/integration/test_foundry_prove.py
  src/tests/unit/test_foundry_prove.py
Labels: automerge, enhancement

#654 Enum constraints
  package/version
  pyproject.toml
  src/kontrol/__init__.py
  src/kontrol/foundry.py
  src/kontrol/kompile.py
  src/kontrol/prove.py
  src/kontrol/solc_to_k.py
  src/tests/integration/test-data/foundry-dependency-all
  src/tests/integration/test-data/foundry/test/Enum.t.sol
  src/tests/integration/test-data/show/Enum.enum_argument_range(uint8).cse.expected
  src/tests/integration/test-data/show/Enum.enum_storage_range().cse.expected
  src/tests/integration/test-data/show/Enum.init.cse.expected
  src/tests/integration/test-data/show/contracts.k.expected
  src/tests/integration/test-data/show/foundry.k.expected
  src/tests/unit/test_solc_to_k.py
Labels: automerge, enhancement

#666 CSE: Check if external function is an event
  package/version
  pyproject.toml
  src/kontrol/__init__.py
  src/kontrol/solc_to_k.py
  src/tests/unit/test_solc_to_k.py
Labels: automerge, bug

#667 Deprecate `klabel` attribute
  package/version
  pyproject.toml
  src/kontrol/__init__.py
  src/kontrol/foundry.py
  src/kontrol/kdist/cheatcodes.md
  src/kontrol/kdist/foundry.md
  src/kontrol/kdist/hevm.md
Labels: automerge

#669 Add links to Telegram channel to `md` files
  CONTRIBUTING.md
  README.md
  docs/external-computation/README.md
  package/version
  pyproject.toml
  src/kontrol/__init__.py
Labels: automerge

#661 fixes for the issues on toml related argument parsing
  package/version
  pyproject.toml
  src/kontrol/__init__.py
  src/kontrol/__main__.py
  src/kontrol/cli.py
  src/tests/unit/test_toml_args.py
Labels: automerge, bug

#664 Update dependency: deps/kevm_release
  deps/k_release
  deps/kevm_release
  flake.lock
  flake.nix
  package/version
  poetry.lock
  pyproject.toml
  src/kontrol/__init__.py
  src/tests/integration/test-data/show/AssumeTest.test_assume_false(uint256,uint256).expected
  src/tests/integration/test-data/show/gas-abstraction.expected
Labels: automerge

#670 update initial values in kontrol.toml
  package/version
  pyproject.toml
  src/kontrol/__init__.py
  src/kontrol/utils.py
Labels: automerge

#671 Fix test collection with CSE and no `--mt`
  package/version
  pyproject.toml
  src/kontrol/__init__.py
  src/kontrol/prove.py
Labels: automerge

#672 kontrol init: Add extra output to foundry.toml
  package/version
  pyproject.toml
  src/kontrol/__init__.py
  src/kontrol/foundry.py
  src/kontrol/utils.py
Labels: automerge

#674 Update dependency: deps/kevm_release
  deps/kevm_release
  flake.lock
  flake.nix
  package/version
  poetry.lock
  pyproject.toml
  src/kontrol/__init__.py
Labels: automerge

#673 Correction: *Int instead of &Int
  package/version
  pyproject.toml
  src/kontrol/__init__.py
  src/tests/integration/test-data/show/CallableStorageTest.test_str().cse.expected
  src/tests/integration/test-data/symbolic-bytes-lemmas.k
Labels: bug

#675 Support expectRevert and expectEmit in CSE
  package/version
  pyproject.toml
  src/kontrol/__init__.py
  src/kontrol/prove.py
  src/tests/integration/test-data/show/AddConst.applyOp(uint256).cse.expected
  src/tests/integration/test-data/show/ArithmeticContract.add(uint256,uint256).cse.expected
  src/tests/integration/test-data/show/ArithmeticContract.add_sub_external(uint256,uint256,uint256).cse.expected
  src/tests/integration/test-data/show/CallableStorageContract.str().cse.expected
  src/tests/integration/test-data/show/Enum.enum_argument_range(uint8).cse.expected
  src/tests/integration/test-data/show/Enum.enum_storage_range().cse.expected
  src/tests/integration/test-data/show/Enum.init.cse.expected
  src/tests/integration/test-data/show/Identity.applyOp(uint256).cse.expected
  src/tests/integration/test-data/show/Identity.identity(uint256).cse.expected
  src/tests/integration/test-data/show/ImportedContract.add(uint256).cse.expected
  src/tests/integration/test-data/show/ImportedContract.count().cse.expected
  src/tests/integration/test-data/show/ImportedContract.init.cse.expected
  src/tests/integration/test-data/show/ImportedContract.set(uint256).cse.expected
  src/tests/integration/test-data/show/StaticCallContract.set(uint256).cse.expected
  src/tests/integration/test-data/show/TGovernance.getEscrowTokenTotalSupply().cse.expected
Labels: automerge

#676 Update dependency: deps/kevm_release
  deps/k_release
  deps/kevm_release
  flake.lock
  flake.nix
  package/version
  poetry.lock
  pyproject.toml
  src/kontrol/__init__.py
Labels: automerge

#681 Temp disable K attribute warnings for deprecated KLabel
  package/version
  pyproject.toml
  src/kontrol/__init__.py
  src/kontrol/kompile.py
Labels: automerge, bug

#682 Skip debug JSON files in from the output directory
  package/version
  pyproject.toml
  src/kontrol/__init__.py
  src/kontrol/foundry.py
Labels: bug

#689 Update dependency: deps/kevm_release
  deps/k_release
  deps/kevm_release
  flake.lock
  flake.nix
  package/version
  poetry.lock
  pyproject.toml
  src/kontrol/__init__.py
  src/kontrol/kompile.py
  src/kontrol/solc_to_k.py
  src/tests/integration/test-data/show/contracts.k.expected
Labels: automerge

#691 Add `--force-sequential` option to kontrol
  package/version
  pyproject.toml
  src/kontrol/__init__.py
  src/kontrol/prove.py
  src/tests/conftest.py
  src/tests/integration/test_foundry_prove.py
  src/tests/integration/test_hevm_prove.py
  src/tests/integration/test_kontrol.py
  src/tests/integration/test_kontrol_cse.py
  src/tests/integration/test_tracing.py
  src/tests/profiling/test_foundry_prove.py
Labels: automerge

#694 Update dependency: deps/kevm_release
  .github/workflows/test-pr.yml
  deps/k_release
  deps/kevm_release
  flake.lock
  flake.nix
  package/version
  poetry.lock
  pyproject.toml
  src/kontrol/__init__.py
Labels: automerge

#690 Replace `run_process` by `run_process_2`
  package/version
  pyproject.toml
  src/kontrol/__init__.py
  src/kontrol/__main__.py
  src/kontrol/foundry.py
  src/kontrol/prove.py
  src/kontrol/solc_to_k.py
  src/tests/integration/conftest.py
  src/tests/utils.py
Labels: automerge

#697 Update dependency: deps/kevm_release
  deps/k_release
  deps/kevm_release
  flake.lock
  flake.nix
  package/version
  poetry.lock
  pyproject.toml
  src/kontrol/__init__.py
Labels: automerge

#692 `kontrol show` to allow full path of contract
  package/version
  pyproject.toml
  src/kontrol/__init__.py
  src/kontrol/foundry.py
Labels: enhancement

#699 Update dependency: deps/kevm_release
  deps/k_release
  deps/kevm_release
  flake.lock
  flake.nix
  package/version
  poetry.lock
  pyproject.toml
  src/kontrol/__init__.py
Labels: automerge

#605 Support of `assertEq` on some dynamic length arrays
  package/version
  pyproject.toml
  src/kontrol/__init__.py
  src/kontrol/kdist/assert.md
  src/tests/integration/test-data/end-to-end-prove-all
  src/tests/integration/test-data/end-to-end-prove-skip
  src/tests/integration/test-data/src/Unit.t.sol
Labels: enhancement

#680 Mock function cheatcode
  .github/workflows/test-pr.yml
  package/version
  pyproject.toml
  src/kontrol/__init__.py
  src/kontrol/kdist/cheatcodes.md
  src/kontrol/prove.py
  src/tests/integration/conftest.py
  src/tests/integration/test-data/foundry-prove-all
  src/tests/integration/test-data/foundry/test/MockFunction.t.sol
  src/tests/integration/test-data/lemmas.k
  src/tests/integration/test-data/show/AccountParamsTest.testDealConcrete().trace.expected
  src/tests/integration/test-data/show/AddConst.applyOp(uint256).cse.expected
  src/tests/integration/test-data/show/AddrTest.test_addr_true().trace.expected
  src/tests/integration/test-data/show/ArithmeticCallTest.test_double_add(uint256,uint256).cse.expected
  src/tests/integration/test-data/show/ArithmeticCallTest.test_double_add_double_sub(uint256,uint256).cse.expected
  src/tests/integration/test-data/show/ArithmeticCallTest.test_double_add_sub_external(uint256,uint256,uint256).cse.expected
  src/tests/integration/test-data/show/ArithmeticContract.add(uint256,uint256).cse.expected
  src/tests/integration/test-data/show/ArithmeticContract.add_sub_external(uint256,uint256,uint256).cse.expected
  src/tests/integration/test-data/show/AssertTest.checkFail_assert_false().expected
  src/tests/integration/test-data/show/AssertTest.testFail_assert_true().expected
  src/tests/integration/test-data/show/AssertTest.testFail_expect_revert().expected
  src/tests/integration/test-data/show/AssertTest.test_assert_false().expected
  src/tests/integration/test-data/show/AssertTest.test_assert_true().expected
  src/tests/integration/test-data/show/AssertTest.test_failing_branch(uint256).expected
  src/tests/integration/test-data/show/AssertTest.test_revert_branch(uint256,uint256).expected
  src/tests/integration/test-data/show/AssumeTest.testFail_assume_false(uint256,uint256).expected
  src/tests/integration/test-data/show/AssumeTest.testFail_assume_true(uint256,uint256).expected
  src/tests/integration/test-data/show/AssumeTest.test_assume_false(uint256,uint256).expected
  src/tests/integration/test-data/show/BlockParamsTest.testWarp(uint256).trace.expected
  src/tests/integration/test-data/show/CSETest.test_add_const(uint256,uint256).cse.expected
  src/tests/integration/test-data/show/CSETest.test_identity(uint256,uint256).cse.expected
  src/tests/integration/test-data/show/CallableStorageContract.str().cse.expected
  src/tests/integration/test-data/show/CallableStorageTest.test_str().cse.expected
  src/tests/integration/test-data/show/ConstructorTest.init.cse.expected
  src/tests/integration/test-data/show/ConstructorTest.test_contract_call().cse.expected
  src/tests/integration/test-data/show/ContractFieldTest.testEscrowToken().cse.expected
  src/tests/integration/test-data/show/Enum.enum_argument_range(uint8).cse.expected
  src/tests/integration/test-data/show/Enum.enum_storage_range().cse.expected
  src/tests/integration/test-data/show/Enum.init.cse.expected
  src/tests/integration/test-data/show/Identity.applyOp(uint256).cse.expected
  src/tests/integration/test-data/show/Identity.identity(uint256).cse.expected
  src/tests/integration/test-data/show/ImportedContract.add(uint256).cse.expected
  src/tests/integration/test-data/show/ImportedContract.count().cse.expected
  src/tests/integration/test-data/show/ImportedContract.init.cse.expected
  src/tests/integration/test-data/show/ImportedContract.set(uint256).cse.expected
  src/tests/integration/test-data/show/InterfaceTagTest.testInterface().cse.expected
  src/tests/integration/test-data/show/SetUpDeployTest.test_extcodesize().expected
  src/tests/integration/test-data/show/StaticCallContract.set(uint256).cse.expected
  src/tests/integration/test-data/show/TGovernance.getEscrowTokenTotalSupply().cse.expected
  src/tests/integration/test-data/show/contracts.k.expected
  src/tests/integration/test-data/show/foundry.k.expected
  src/tests/integration/test-data/show/gas-abstraction.expected
  src/tests/integration/test-data/show/merge-loop-heads.expected
  src/tests/integration/test-data/show/minimized/AssertTest.testFail_expect_revert().expected
  src/tests/integration/test-data/show/minimized/AssertTest.test_assert_false().expected
  src/tests/integration/test-data/show/minimized/AssertTest.test_failing_branch(uint256).expected
  src/tests/integration/test-data/show/minimized/AssertTest.test_revert_branch(uint256,uint256).expected
  src/tests/integration/test-data/show/node-refutation.expected
  src/tests/integration/test-data/show/split-node.expected
Labels: automerge

#705 Update dependency: deps/kevm_release
  deps/k_release
  deps/kevm_release
  flake.lock
  flake.nix
  package/version
  poetry.lock
  pyproject.toml
  src/kontrol/__init__.py
Labels: automerge

#701 Generate `_notExternalAddress` function in RecordedState
  package/version
  pyproject.toml
  src/kontrol/__init__.py
  src/kontrol/state_record.py
  src/tests/integration/test-data/foundry/src/LoadStateDiff.sol
  src/tests/integration/test-data/foundry/src/LoadStateDump.sol
  src/tests/integration/test-data/show/contracts.k.expected
Labels: automerge, enhancement

#707 Enable Public PR Submissions to run Testing.
  .github/workflows/master-push.yml
  .github/workflows/release.yml
  .github/workflows/test-pr.yml
  .github/workflows/update-version.yml
Labels: automerge

#708 Missed a reference to the default branch
  .github/workflows/master-push.yml
Labels: automerge

#709 Whitelist storage: use List instead of Set
  src/kontrol/kdist/cheatcodes.md
  src/kontrol/prove.py
  src/tests/integration/test-data/foundry-prove-skip-legacy
  src/tests/integration/test-data/show/AccountParamsTest.testDealConcrete().trace.expected
  src/tests/integration/test-data/show/AddConst.applyOp(uint256).cse.expected
  src/tests/integration/test-data/show/AddrTest.test_addr_true().trace.expected
  src/tests/integration/test-data/show/ArithmeticCallTest.test_double_add(uint256,uint256).cse.expected
  src/tests/integration/test-data/show/ArithmeticCallTest.test_double_add_double_sub(uint256,uint256).cse.expected
  src/tests/integration/test-data/show/ArithmeticCallTest.test_double_add_sub_external(uint256,uint256,uint256).cse.expected
  src/tests/integration/test-data/show/ArithmeticContract.add(uint256,uint256).cse.expected
  src/tests/integration/test-data/show/ArithmeticContract.add_sub_external(uint256,uint256,uint256).cse.expected
  src/tests/integration/test-data/show/AssertTest.checkFail_assert_false().expected
  src/tests/integration/test-data/show/AssertTest.testFail_assert_true().expected
  src/tests/integration/test-data/show/AssertTest.testFail_expect_revert().expected
  src/tests/integration/test-data/show/AssertTest.test_assert_false().expected
  src/tests/integration/test-data/show/AssertTest.test_assert_true().expected
  src/tests/integration/test-data/show/AssertTest.test_failing_branch(uint256).expected
  src/tests/integration/test-data/show/AssertTest.test_revert_branch(uint256,uint256).expected
  src/tests/integration/test-data/show/AssumeTest.testFail_assume_false(uint256,uint256).expected
  src/tests/integration/test-data/show/AssumeTest.testFail_assume_true(uint256,uint256).expected
  src/tests/integration/test-data/show/AssumeTest.test_assume_false(uint256,uint256).expected
  src/tests/integration/test-data/show/BlockParamsTest.testWarp(uint256).trace.expected
  src/tests/integration/test-data/show/CSETest.test_add_const(uint256,uint256).cse.expected
  src/tests/integration/test-data/show/CSETest.test_identity(uint256,uint256).cse.expected
  src/tests/integration/test-data/show/CallableStorageContract.str().cse.expected
  src/tests/integration/test-data/show/CallableStorageTest.test_str().cse.expected
  src/tests/integration/test-data/show/ConstructorTest.init.cse.expected
  src/tests/integration/test-data/show/ConstructorTest.test_contract_call().cse.expected
  src/tests/integration/test-data/show/ContractFieldTest.testEscrowToken().cse.expected
  src/tests/integration/test-data/show/Enum.enum_argument_range(uint8).cse.expected
  src/tests/integration/test-data/show/Enum.enum_storage_range().cse.expected
  src/tests/integration/test-data/show/Enum.init.cse.expected
  src/tests/integration/test-data/show/Identity.applyOp(uint256).cse.expected
  src/tests/integration/test-data/show/Identity.identity(uint256).cse.expected
  src/tests/integration/test-data/show/ImportedContract.add(uint256).cse.expected
  src/tests/integration/test-data/show/ImportedContract.count().cse.expected
  src/tests/integration/test-data/show/ImportedContract.init.cse.expected
  src/tests/integration/test-data/show/ImportedContract.set(uint256).cse.expected
  src/tests/integration/test-data/show/InterfaceTagTest.testInterface().cse.expected
  src/tests/integration/test-data/show/SetUpDeployTest.test_extcodesize().expected
  src/tests/integration/test-data/show/StaticCallContract.set(uint256).cse.expected
  src/tests/integration/test-data/show/TGovernance.getEscrowTokenTotalSupply().cse.expected
  src/tests/integration/test-data/show/gas-abstraction.expected
  src/tests/integration/test-data/show/merge-loop-heads.expected
  src/tests/integration/test-data/show/minimized/AssertTest.testFail_expect_revert().expected
  src/tests/integration/test-data/show/minimized/AssertTest.test_assert_false().expected
  src/tests/integration/test-data/show/minimized/AssertTest.test_failing_branch(uint256).expected
  src/tests/integration/test-data/show/minimized/AssertTest.test_revert_branch(uint256,uint256).expected
  src/tests/integration/test-data/show/node-refutation.expected
  src/tests/integration/test-data/show/split-node.expected
Labels: automerge

#687 Add option to omit enum constraints
  src/kontrol/__main__.py
  src/kontrol/cli.py
  src/kontrol/foundry.py
  src/kontrol/options.py
  src/kontrol/prove.py
  src/kontrol/solc_to_k.py
  src/tests/integration/conftest.py
  src/tests/integration/test_kontrol_cse.py
Labels: automerge

#718 Update dependency: deps/kevm_release
  deps/kevm_release
  flake.lock
  flake.nix
  poetry.lock
  pyproject.toml
Labels: automerge

#663 Support symbolic contract storage slots with nonzero offsets
  src/kontrol/prove.py
  src/tests/integration/test-data/cse-lemmas.k
  src/tests/integration/test-data/foundry/test/ContractFieldTest.t.sol
  src/tests/integration/test-data/show/ContractFieldTest.testEscrowToken().cse.expected
  src/tests/integration/test-data/show/TGovernance.getEscrowTokenTotalSupply().cse.expected
  src/tests/integration/test-data/symbolic-bytes-lemmas.k
Labels: automerge

#717 Small tweaks to foundry_kompile
  src/kontrol/foundry.py
Labels: automerge, bug

#719 Update dependency: deps/kevm_release
  deps/k_release
  deps/kevm_release
  flake.lock
  flake.nix
  poetry.lock
  pyproject.toml
  src/tests/integration/test-data/show/CSETest.test_add_const(uint256,uint256).cse.expected
  src/tests/integration/test-data/show/CSETest.test_identity(uint256,uint256).cse.expected
  src/tests/integration/test-data/show/CallableStorageContract.str().cse.expected
  src/tests/integration/test-data/show/Enum.enum_storage_range().cse.expected
  src/tests/integration/test-data/show/Enum.init.cse.expected
Labels: automerge

#721 Update dependency: deps/kevm_release
  deps/k_release
  deps/kevm_release
  flake.lock
  flake.nix
  poetry.lock
  pyproject.toml
Labels: automerge

#722 Update dependency: deps/kevm_release
  deps/k_release
  deps/kevm_release
  flake.lock
  flake.nix
  poetry.lock
  pyproject.toml
Labels: automerge

#720 KCFG Readability improvements
  src/kontrol/__main__.py
  src/kontrol/cli.py
  src/kontrol/foundry.py
  src/kontrol/options.py
  src/kontrol/solc_to_k.py
  src/tests/integration/test-data/show/AccountParamsTest.testDealConcrete().trace.expected
  src/tests/integration/test-data/show/AddConst.applyOp(uint256).cse.expected
  src/tests/integration/test-data/show/AddrTest.test_addr_true().trace.expected
  src/tests/integration/test-data/show/ArithmeticCallTest.test_double_add(uint256,uint256).cse.expected
  src/tests/integration/test-data/show/ArithmeticCallTest.test_double_add_double_sub(uint256,uint256).cse.expected
  src/tests/integration/test-data/show/ArithmeticCallTest.test_double_add_sub_external(uint256,uint256,uint256).cse.expected
  src/tests/integration/test-data/show/ArithmeticContract.add(uint256,uint256).cse.expected
  src/tests/integration/test-data/show/ArithmeticContract.add_sub_external(uint256,uint256,uint256).cse.expected
  src/tests/integration/test-data/show/AssertTest.checkFail_assert_false().expected
  src/tests/integration/test-data/show/AssertTest.testFail_assert_true().expected
  src/tests/integration/test-data/show/AssertTest.testFail_expect_revert().expected
  src/tests/integration/test-data/show/AssertTest.test_assert_false().expected
  src/tests/integration/test-data/show/AssertTest.test_assert_true().expected
  src/tests/integration/test-data/show/AssertTest.test_failing_branch(uint256).expected
  src/tests/integration/test-data/show/AssertTest.test_revert_branch(uint256,uint256).expected
  src/tests/integration/test-data/show/AssumeTest.testFail_assume_false(uint256,uint256).expected
  src/tests/integration/test-data/show/AssumeTest.testFail_assume_true(uint256,uint256).expected
  src/tests/integration/test-data/show/AssumeTest.test_assume_false(uint256,uint256).expected
  src/tests/integration/test-data/show/BlockParamsTest.testWarp(uint256).trace.expected
  src/tests/integration/test-data/show/CSETest.test_add_const(uint256,uint256).cse.expected
  src/tests/integration/test-data/show/CSETest.test_identity(uint256,uint256).cse.expected
  src/tests/integration/test-data/show/CallableStorageContract.str().cse.expected
  src/tests/integration/test-data/show/CallableStorageTest.test_str().cse.expected
  src/tests/integration/test-data/show/ConstructorTest.test_contract_call().cse.expected
  src/tests/integration/test-data/show/ContractFieldTest.testEscrowToken().cse.expected
  src/tests/integration/test-data/show/Enum.enum_argument_range(uint8).cse.expected
  src/tests/integration/test-data/show/Enum.enum_storage_range().cse.expected
  src/tests/integration/test-data/show/Identity.applyOp(uint256).cse.expected
  src/tests/integration/test-data/show/Identity.identity(uint256).cse.expected
  src/tests/integration/test-data/show/ImportedContract.add(uint256).cse.expected
  src/tests/integration/test-data/show/ImportedContract.count().cse.expected
  src/tests/integration/test-data/show/ImportedContract.set(uint256).cse.expected
  src/tests/integration/test-data/show/InterfaceTagTest.testInterface().cse.expected
  src/tests/integration/test-data/show/SetUpDeployTest.test_extcodesize().expected
  src/tests/integration/test-data/show/StaticCallContract.set(uint256).cse.expected
  src/tests/integration/test-data/show/TGovernance.getEscrowTokenTotalSupply().cse.expected
  src/tests/integration/test-data/show/gas-abstraction.expected
  src/tests/integration/test-data/show/merge-loop-heads.expected
  src/tests/integration/test-data/show/minimized/AssertTest.testFail_expect_revert().expected
  src/tests/integration/test-data/show/minimized/AssertTest.test_assert_false().expected
  src/tests/integration/test-data/show/minimized/AssertTest.test_failing_branch(uint256).expected
  src/tests/integration/test-data/show/minimized/AssertTest.test_revert_branch(uint256,uint256).expected
  src/tests/integration/test-data/show/node-refutation.expected
  src/tests/integration/test-data/show/split-node.expected
Labels: automerge, enhancement, engagement

#723 Update dependency: deps/kevm_release
  deps/kevm_release
  flake.lock
  flake.nix
  poetry.lock
  pyproject.toml
Labels: automerge

#724 Fix code lookup not accounting for linkReference placeholder
  src/kontrol/foundry.py
  src/kontrol/solc_to_k.py
  src/tests/integration/test-data/show/AssertTest.testFail_assert_true().expected
  src/tests/integration/test-data/show/AssertTest.testFail_expect_revert().expected
  src/tests/integration/test-data/show/AssertTest.test_assert_false().expected
  src/tests/integration/test-data/show/AssertTest.test_failing_branch(uint256).expected
  src/tests/integration/test-data/show/AssertTest.test_revert_branch(uint256,uint256).expected
  src/tests/integration/test-data/show/AssumeTest.testFail_assume_false(uint256,uint256).expected
  src/tests/integration/test-data/show/AssumeTest.test_assume_false(uint256,uint256).expected
  src/tests/integration/test-data/show/gas-abstraction.expected
  src/tests/integration/test-data/show/merge-loop-heads.expected
  src/tests/integration/test-data/show/minimized/AssertTest.testFail_expect_revert().expected
  src/tests/integration/test-data/show/minimized/AssertTest.test_assert_false().expected
  src/tests/integration/test-data/show/minimized/AssertTest.test_failing_branch(uint256).expected
  src/tests/integration/test-data/show/minimized/AssertTest.test_revert_branch(uint256,uint256).expected
  src/tests/unit/test_solc_to_k.py
Labels: automerge, bug, engagement

#726 Don't attempt to hex encode contract names
  src/kontrol/foundry.py
  src/tests/integration/test_foundry_prove.py
Labels: bug

#730 Update dependency: deps/kevm_release
  deps/kevm_release
  flake.lock
  flake.nix
  poetry.lock
  pyproject.toml
Labels: automerge

#732 Update dependency: deps/kevm_release
  deps/k_release
  deps/kevm_release
  flake.lock
  flake.nix
  poetry.lock
  pyproject.toml
Labels: automerge

#733 Update dependency: deps/kevm_release
  deps/kevm_release
  flake.lock
  flake.nix
  poetry.lock
  pyproject.toml
Labels: automerge
