Repository runtimeverification/kontrol, pull requests merged in 2024-06, with the labels that each got.

#595 Update dependency: deps/kevm_release
  deps/k_release
  deps/kevm_release
  flake.lock
  flake.nix
  package/version
  poetry.lock
  pyproject.toml
  src/kontrol/__init__.py
Labels: automerge

#598 Disable break-on-calls if the test output is not checked in integration tests.
  package/version
  pyproject.toml
  src/kontrol/__init__.py
  src/tests/integration/test_foundry_prove.py
Labels: automerge, enhancement

#593 Support of `assertApproxEqRel` cheatcode
  package/version
  pyproject.toml
  src/kontrol/__init__.py
  src/kontrol/kdist/assert.md
  src/tests/integration/test-data/end-to-end-prove-all
  src/tests/integration/test-data/end-to-end-prove-skip
  src/tests/integration/test-data/src/Unit.t.sol
Labels: automerge, enhancement

#604 Update dependency: deps/kevm_release
  deps/k_release
  deps/kevm_release
  flake.lock
  flake.nix
  package/version
  poetry.lock
  pyproject.toml
  src/kontrol/__init__.py
Labels: automerge

#606 Update dependency: deps/kevm_release
  deps/k_release
  deps/kevm_release
  flake.lock
  flake.nix
  package/version
  poetry.lock
  pyproject.toml
  src/kontrol/__init__.py
  src/kontrol/prove.py
Labels: automerge

#607 Remove `KompiledKore` caching from `foundry_kompile`
  package/version
  pyproject.toml
  src/kontrol/__init__.py
  src/kontrol/kompile.py
Labels: automerge

#611 Update dependency: deps/kevm_release
  deps/kevm_release
  flake.lock
  flake.nix
  package/version
  poetry.lock
  pyproject.toml
  src/kontrol/__init__.py
Labels: automerge

#612 Append constructor args to runtime bytecode
  package/version
  pyproject.toml
  src/kontrol/__init__.py
  src/kontrol/prove.py
  src/kontrol/solc_to_k.py
  src/tests/integration/test-data/foundry-init-code
  src/tests/integration/test-data/foundry/test/ConstructorTest.t.sol
  src/tests/integration/test-data/show/ConstructorTest.init.cse.expected
  src/tests/integration/test-data/show/ConstructorTest.test_contract_call().cse.expected
  src/tests/integration/test-data/show/ImportedContract.init.cse.expected
  src/tests/integration/test-data/show/contracts.k.expected
  src/tests/integration/test-data/show/foundry.k.expected
Labels: automerge

#618 Update dependency: deps/kevm_release
  deps/k_release
  deps/kevm_release
  flake.lock
  flake.nix
  package/version
  poetry.lock
  pyproject.toml
  src/kontrol/__init__.py
Labels: automerge

#621 Update dependency: deps/kevm_release
  deps/k_release
  deps/kevm_release
  flake.lock
  flake.nix
  package/version
  poetry.lock
  pyproject.toml
  src/kontrol/__init__.py
Labels: automerge

#625 Update dependency: deps/kevm_release
  deps/kevm_release
  flake.lock
  flake.nix
  package/version
  poetry.lock
  pyproject.toml
  src/kontrol/__init__.py
Labels: automerge

#627 String storage fix
  package/version
  pyproject.toml
  src/kontrol/__init__.py
  src/kontrol/prove.py
  src/tests/integration/test-data/foundry-dependency-all
  src/tests/integration/test-data/foundry/test/CallableStorageTest.t.sol
  src/tests/integration/test-data/show/CallableStorageContract.str().cse.expected
  src/tests/integration/test-data/show/CallableStorageTest.test_str().cse.expected
  src/tests/integration/test-data/show/contracts.k.expected
  src/tests/integration/test-data/show/foundry.k.expected
  src/tests/integration/test_kontrol_cse.py
Labels: automerge

#632 Refactor `method_sig_from_abi` to handle `struct[][]`
  package/version
  pyproject.toml
  src/kontrol/__init__.py
  src/kontrol/solc_to_k.py
  src/tests/integration/test-data/foundry/test/DynamicTypes.t.sol
  src/tests/integration/test-data/show/contracts.k.expected
Labels: automerge

#634 Remove convoluted kontrol-pyk package setup
  flake.nix
  package/version
  pyproject.toml
  src/kontrol/__init__.py
Labels: automerge

#626 Update dependency: deps/kevm_release
  deps/k_release
  deps/kevm_release
  flake.lock
  flake.nix
  package/version
  poetry.lock
  pyproject.toml
  src/kontrol/__init__.py
  src/tests/integration/test-data/show/ArithmeticCallTest.test_double_add(uint256,uint256).cse.expected
  src/tests/integration/test-data/show/ArithmeticCallTest.test_double_add_double_sub(uint256,uint256).cse.expected
  src/tests/integration/test-data/show/ArithmeticCallTest.test_double_add_sub_external(uint256,uint256,uint256).cse.expected
  src/tests/integration/test-data/show/AssertTest.checkFail_assert_false().expected
  src/tests/integration/test-data/show/AssertTest.testFail_assert_true().expected
  src/tests/integration/test-data/show/AssertTest.testFail_expect_revert().expected
  src/tests/integration/test-data/show/AssertTest.test_assert_false().expected
  src/tests/integration/test-data/show/AssertTest.test_assert_true().expected
  src/tests/integration/test-data/show/AssertTest.test_failing_branch(uint256).expected
  src/tests/integration/test-data/show/AssertTest.test_revert_branch(uint256,uint256).expected
  src/tests/integration/test-data/show/AssumeTest.testFail_assume_false(uint256,uint256).expected
  src/tests/integration/test-data/show/AssumeTest.testFail_assume_true(uint256,uint256).expected
  src/tests/integration/test-data/show/AssumeTest.test_assume_false(uint256,uint256).expected
  src/tests/integration/test-data/show/CSETest.test_add_const(uint256,uint256).cse.expected
  src/tests/integration/test-data/show/CSETest.test_identity(uint256,uint256).cse.expected
  src/tests/integration/test-data/show/SetUpDeployTest.test_extcodesize().expected
  src/tests/integration/test-data/show/gas-abstraction.expected
  src/tests/integration/test-data/show/merge-loop-heads.expected
  src/tests/integration/test-data/show/minimized/AssertTest.testFail_expect_revert().expected
  src/tests/integration/test-data/show/minimized/AssertTest.test_assert_false().expected
  src/tests/integration/test-data/show/minimized/AssertTest.test_failing_branch(uint256).expected
  src/tests/integration/test-data/show/minimized/AssertTest.test_revert_branch(uint256,uint256).expected
  src/tests/integration/test-data/show/node-refutation.expected
  src/tests/integration/test-data/show/split-node.expected
Labels: automerge

#644 Update dependency: deps/kevm_release
  deps/k_release
  deps/kevm_release
  flake.lock
  flake.nix
  package/version
  poetry.lock
  pyproject.toml
  src/kontrol/__init__.py
Labels: automerge

#640 Fix --evm-tracing CLI parameter.
  package/version
  pyproject.toml
  src/kontrol/__init__.py
  src/kontrol/cli.py
Labels: automerge

#645 Update dependency: deps/kevm_release
  deps/kevm_release
  flake.lock
  flake.nix
  package/version
  poetry.lock
  pyproject.toml
  src/kontrol/__init__.py
Labels: automerge

#642 Add pretty feedback from Kontrol
  package/version
  pyproject.toml
  src/kontrol/__init__.py
  src/kontrol/__main__.py
  src/kontrol/prove.py
Labels: automerge, enhancement

#646 change rekompilation conditions and fix inclusion of setup function into proof
  .gitignore
  package/version
  pyproject.toml
  src/kontrol/__init__.py
  src/kontrol/foundry.py
  src/kontrol/kompile.py
Labels: automerge, bug

#635 Refining cse storage generation
  package/version
  pyproject.toml
  src/kontrol/__init__.py
  src/kontrol/__main__.py
  src/kontrol/foundry.py
  src/kontrol/prove.py
  src/tests/integration/test-data/show/AccountParamsTest.testDealConcrete().trace.expected
  src/tests/integration/test-data/show/AddConst.applyOp(uint256).cse.expected
  src/tests/integration/test-data/show/AddrTest.test_addr_true().trace.expected
  src/tests/integration/test-data/show/ArithmeticContract.add(uint256,uint256).cse.expected
  src/tests/integration/test-data/show/ArithmeticContract.add_sub_external(uint256,uint256,uint256).cse.expected
  src/tests/integration/test-data/show/AssertTest.checkFail_assert_false().expected
  src/tests/integration/test-data/show/AssertTest.testFail_assert_true().expected
  src/tests/integration/test-data/show/AssertTest.testFail_expect_revert().expected
  src/tests/integration/test-data/show/AssertTest.test_assert_false().expected
  src/tests/integration/test-data/show/AssertTest.test_assert_true().expected
  src/tests/integration/test-data/show/AssertTest.test_failing_branch(uint256).expected
  src/tests/integration/test-data/show/AssertTest.test_revert_branch(uint256,uint256).expected
  src/tests/integration/test-data/show/AssumeTest.testFail_assume_false(uint256,uint256).expected
  src/tests/integration/test-data/show/AssumeTest.testFail_assume_true(uint256,uint256).expected
  src/tests/integration/test-data/show/AssumeTest.test_assume_false(uint256,uint256).expected
  src/tests/integration/test-data/show/BlockParamsTest.testWarp(uint256).trace.expected
  src/tests/integration/test-data/show/CallableStorageContract.str().cse.expected
  src/tests/integration/test-data/show/CallableStorageTest.test_str().cse.expected
  src/tests/integration/test-data/show/ConstructorTest.init.cse.expected
  src/tests/integration/test-data/show/Identity.applyOp(uint256).cse.expected
  src/tests/integration/test-data/show/Identity.identity(uint256).cse.expected
  src/tests/integration/test-data/show/ImportedContract.add(uint256).cse.expected
  src/tests/integration/test-data/show/ImportedContract.count().cse.expected
  src/tests/integration/test-data/show/ImportedContract.init.cse.expected
  src/tests/integration/test-data/show/ImportedContract.set(uint256).cse.expected
  src/tests/integration/test-data/show/SetUpDeployTest.test_extcodesize().expected
  src/tests/integration/test-data/show/StaticCallContract.set(uint256).cse.expected
  src/tests/integration/test-data/show/TGovernance.getEscrowTokenTotalSupply().cse.expected
  src/tests/integration/test-data/show/gas-abstraction.expected
  src/tests/integration/test-data/show/merge-loop-heads.expected
  src/tests/integration/test-data/show/minimized/AssertTest.testFail_expect_revert().expected
  src/tests/integration/test-data/show/minimized/AssertTest.test_assert_false().expected
  src/tests/integration/test-data/show/minimized/AssertTest.test_failing_branch(uint256).expected
  src/tests/integration/test-data/show/minimized/AssertTest.test_revert_branch(uint256,uint256).expected
  src/tests/integration/test-data/show/node-refutation.expected
  src/tests/integration/test-data/show/split-node.expected
  src/tests/integration/test-data/symbolic-bytes-lemmas.k
Labels: automerge, enhancement

#656 Update pretty printing & remove transient messages
  package/version
  pyproject.toml
  src/kontrol/__init__.py
  src/kontrol/__main__.py
  src/kontrol/kompile.py
  src/kontrol/prove.py
  src/kontrol/utils.py
Labels: automerge, bug, enhancement

#655 Update dependency: deps/kevm_release
  .github/workflows/test-pr.yml
  deps/k_release
  deps/kevm_release
  flake.lock
  flake.nix
  package/version
  poetry.lock
  pyproject.toml
  src/kontrol/__init__.py
Labels: automerge

#636 Silence `kontrol build` warnings
  package/version
  pyproject.toml
  src/kontrol/__init__.py
  src/kontrol/cli.py
  src/kontrol/kompile.py
  src/kontrol/options.py
Labels: automerge, enhancement
