Repository runtimeverification/kontrol, pull requests merged in 2024-04, with the labels that each got.

#497 Update dependency: deps/kevm_release
  deps/k_release
  deps/kevm_release
  flake.lock
  flake.nix
  package/version
  poetry.lock
  pyproject.toml
  src/kontrol/__init__.py
  src/kontrol/foundry.py
  src/kontrol/prove.py
Labels: automerge

#467 Control reinitializing of the proof's `setUp` function
  package/version
  pyproject.toml
  src/kontrol/__init__.py
  src/kontrol/__main__.py
  src/kontrol/foundry.py
  src/kontrol/options.py
  src/kontrol/prove.py
  src/tests/integration/test_foundry_prove.py
Labels: automerge, enhancement

#499 #call_foundry refactor
  CONTRIBUTING.md
  package/version
  pyproject.toml
  src/kontrol/__init__.py
  src/kontrol/kdist/cheatcodes.md
  src/kontrol/kdist/foundry.md
Labels: automerge, enhancement

#445 Update master-push.yml
  .github/workflows/master-push.yml
  package/version
  pyproject.toml
  src/kontrol/__init__.py
Labels: automerge

#502 Update dependency: deps/kevm_release
  deps/kevm_release
  flake.lock
  flake.nix
  package/version
  poetry.lock
  pyproject.toml
  src/kontrol/__init__.py
Labels: automerge

#503 Add option to pretty print in hex encoding
  package/version
  pyproject.toml
  src/kontrol/__init__.py
  src/kontrol/__main__.py
  src/kontrol/foundry.py
Labels: automerge, enhancement, cli

#504 Update dependency: deps/kevm_release
  deps/k_release
  deps/kevm_release
  flake.lock
  flake.nix
  package/version
  poetry.lock
  pyproject.toml
  src/kontrol/__init__.py
Labels: automerge

#469 Trace EVM execution in Kontrol
  package/version
  pyproject.toml
  src/kontrol/__init__.py
  src/kontrol/__main__.py
  src/kontrol/kdist/foundry.md
  src/kontrol/kdist/trace.md
  src/kontrol/options.py
  src/kontrol/prove.py
  src/tests/integration/test-data/foundry-prove-skip
  src/tests/integration/test-data/foundry-trace-all
  src/tests/integration/test-data/foundry-trace-skip
  src/tests/integration/test-data/show/AccountParamsTest.testDealConcrete().trace.expected
  src/tests/integration/test-data/show/AddrTest.test_addr_true().trace.expected
  src/tests/integration/test-data/show/AssertTest.checkFail_assert_false().expected
  src/tests/integration/test-data/show/AssertTest.testFail_assert_true().expected
  src/tests/integration/test-data/show/AssertTest.testFail_expect_revert().expected
  src/tests/integration/test-data/show/AssertTest.test_assert_false().expected
  src/tests/integration/test-data/show/AssertTest.test_assert_true().expected
  src/tests/integration/test-data/show/AssertTest.test_assert_true().trace.expected
  src/tests/integration/test-data/show/AssertTest.test_failing_branch(uint256).expected
  src/tests/integration/test-data/show/AssertTest.test_revert_branch(uint256,uint256).expected
  src/tests/integration/test-data/show/AssumeTest.testFail_assume_false(uint256,uint256).expected
  src/tests/integration/test-data/show/AssumeTest.testFail_assume_true(uint256,uint256).expected
  src/tests/integration/test-data/show/AssumeTest.test_assume_false(uint256,uint256).expected
  src/tests/integration/test-data/show/BlockParamsTest.testWarp(uint256).trace.expected
  src/tests/integration/test-data/show/SetUpDeployTest.test_extcodesize().expected
  src/tests/integration/test-data/show/gas-abstraction.expected
  src/tests/integration/test-data/show/merge-loop-heads.expected
  src/tests/integration/test-data/show/node-refutation.expected
  src/tests/integration/test-data/show/split-node.expected
  src/tests/integration/test_tracing.py
Labels: automerge, enhancement

#508 Update dependency: deps/kevm_release
  deps/k_release
  deps/kevm_release
  flake.lock
  flake.nix
  package/version
  poetry.lock
  pyproject.toml
  src/kontrol/__init__.py
Labels: automerge

#506 Proof execution time is updated when proof is reloaded
  package/version
  pyproject.toml
  src/kontrol/__init__.py
  src/kontrol/prove.py
Labels: automerge, bug

#490 report SMT timeout errors
  package/version
  pyproject.toml
  src/kontrol/__init__.py
  src/kontrol/__main__.py
Labels: automerge, enhancement

#440 Add init and clean commands
  package/version
  pyproject.toml
  src/kontrol/__init__.py
  src/kontrol/__main__.py
  src/kontrol/utils.py
Labels: automerge, enhancement

#501 Add options classes
  package/version
  pyproject.toml
  src/kontrol/__init__.py
  src/kontrol/__main__.py
  src/kontrol/cli.py
  src/kontrol/foundry.py
  src/kontrol/kompile.py
  src/kontrol/prove.py
  src/kontrol/solc_to_k.py
  src/tests/integration/conftest.py
  src/tests/integration/test_foundry_prove.py
  src/tests/integration/test_hevm_prove.py
  src/tests/integration/test_kontrol_cse.py
  src/tests/integration/test_tracing.py
  src/tests/integration/utils.py
  src/tests/profiling/test_foundry_prove.py
Labels: automerge, enhancement

#514 Fix 'regen' referenced before assignment
  package/version
  pyproject.toml
  src/kontrol/__init__.py
  src/kontrol/kompile.py
Labels: automerge, bug

#515 Update dependency: deps/kevm_release
  deps/kevm_release
  flake.lock
  flake.nix
  package/version
  poetry.lock
  pyproject.toml
  src/kontrol/__init__.py
Labels: automerge

#495 Update `merge-nodes` for merging nodes within the same loop
  package/version
  pyproject.toml
  src/kontrol/__init__.py
  src/kontrol/foundry.py
  src/tests/integration/test-data/show/merge-loop-heads.expected
  src/tests/integration/test_foundry_prove.py
Labels: automerge, enhancement

#494 Update source build instructions with secp256k1
  CONTRIBUTING.md
  README.md
  package/version
  pyproject.toml
  src/kontrol/__init__.py
Labels: automerge

#516 Update dependency: deps/kevm_release
  .github/workflows/test-pr.yml
  .github/workflows/update-version.yml
  deps/k_release
  deps/kevm_release
  flake.lock
  flake.nix
  package/version
  poetry.lock
  pyproject.toml
  src/kontrol/__init__.py
  src/kontrol/__main__.py
  src/kontrol/kompile.py
  src/tests/integration/test-data/show/AccountParamsTest.testDealConcrete().trace.expected
  src/tests/integration/test-data/show/AddrTest.test_addr_true().trace.expected
  src/tests/integration/test-data/show/AssertTest.checkFail_assert_false().expected
  src/tests/integration/test-data/show/AssertTest.testFail_assert_true().expected
  src/tests/integration/test-data/show/AssertTest.testFail_expect_revert().expected
  src/tests/integration/test-data/show/AssertTest.test_assert_false().expected
  src/tests/integration/test-data/show/AssertTest.test_assert_true().expected
  src/tests/integration/test-data/show/AssertTest.test_failing_branch(uint256).expected
  src/tests/integration/test-data/show/AssertTest.test_revert_branch(uint256,uint256).expected
  src/tests/integration/test-data/show/AssumeTest.testFail_assume_false(uint256,uint256).expected
  src/tests/integration/test-data/show/AssumeTest.testFail_assume_true(uint256,uint256).expected
  src/tests/integration/test-data/show/AssumeTest.test_assume_false(uint256,uint256).expected
  src/tests/integration/test-data/show/BlockParamsTest.testWarp(uint256).trace.expected
  src/tests/integration/test-data/show/SetUpDeployTest.test_extcodesize().expected
  src/tests/integration/test-data/show/gas-abstraction.expected
  src/tests/integration/test-data/show/merge-loop-heads.expected
  src/tests/integration/test-data/show/minimized/AssertTest.testFail_expect_revert().expected
  src/tests/integration/test-data/show/minimized/AssertTest.test_assert_false().expected
  src/tests/integration/test-data/show/minimized/AssertTest.test_failing_branch(uint256).expected
  src/tests/integration/test-data/show/minimized/AssertTest.test_revert_branch(uint256,uint256).expected
  src/tests/integration/test-data/show/node-refutation.expected
  src/tests/integration/test-data/show/split-node.expected
Labels: automerge

#524 Update dependency: deps/kevm_release
  deps/k_release
  deps/kevm_release
  flake.lock
  flake.nix
  package/version
  poetry.lock
  pyproject.toml
  src/kontrol/__init__.py
Labels: automerge

#527 Update dependency: deps/kevm_release
  deps/k_release
  deps/kevm_release
  flake.lock
  flake.nix
  package/version
  poetry.lock
  pyproject.toml
  src/kontrol/__init__.py
  src/kontrol/foundry.py
  src/kontrol/kompile.py
  src/kontrol/solc_to_k.py
  src/tests/integration/test-data/show/AccountParamsTest.testDealConcrete().trace.expected
  src/tests/integration/test-data/show/AddrTest.test_addr_true().trace.expected
  src/tests/integration/test-data/show/ArithmeticCallTest.test_double_add_double_sub(uint256,uint256).cse.expected
  src/tests/integration/test-data/show/ArithmeticCallTest.test_double_add_sub_external(uint256,uint256,uint256).cse.expected
  src/tests/integration/test-data/show/ArithmeticContract.add_sub_external(uint256,uint256,uint256).cse.expected
  src/tests/integration/test-data/show/AssertTest.checkFail_assert_false().expected
  src/tests/integration/test-data/show/AssertTest.testFail_assert_true().expected
  src/tests/integration/test-data/show/AssertTest.testFail_expect_revert().expected
  src/tests/integration/test-data/show/AssertTest.test_assert_false().expected
  src/tests/integration/test-data/show/AssertTest.test_assert_true().expected
  src/tests/integration/test-data/show/AssertTest.test_failing_branch(uint256).expected
  src/tests/integration/test-data/show/AssertTest.test_revert_branch(uint256,uint256).expected
  src/tests/integration/test-data/show/AssumeTest.testFail_assume_false(uint256,uint256).expected
  src/tests/integration/test-data/show/AssumeTest.testFail_assume_true(uint256,uint256).expected
  src/tests/integration/test-data/show/AssumeTest.test_assume_false(uint256,uint256).expected
  src/tests/integration/test-data/show/BlockParamsTest.testWarp(uint256).trace.expected
  src/tests/integration/test-data/show/SetUpDeployTest.test_extcodesize().expected
  src/tests/integration/test-data/show/gas-abstraction.expected
  src/tests/integration/test-data/show/merge-loop-heads.expected
  src/tests/integration/test-data/show/minimized/AssertTest.testFail_expect_revert().expected
  src/tests/integration/test-data/show/minimized/AssertTest.test_assert_false().expected
  src/tests/integration/test-data/show/minimized/AssertTest.test_failing_branch(uint256).expected
  src/tests/integration/test-data/show/minimized/AssertTest.test_revert_branch(uint256,uint256).expected
  src/tests/integration/test-data/show/node-refutation.expected
  src/tests/integration/test-data/show/split-node.expected
  src/tests/integration/test_foundry_prove.py
Labels: automerge

#529 Update dependency: deps/kevm_release
  deps/kevm_release
  flake.lock
  flake.nix
  package/version
  poetry.lock
  pyproject.toml
  src/kontrol/__init__.py
Labels: automerge

#519 support for `expectRevert(bytes4)`
  package/version
  pyproject.toml
  src/kontrol/__init__.py
  src/kontrol/kdist/cheatcodes.md
  src/tests/integration/test-data/foundry-prove-skip
  src/tests/integration/test-data/foundry-prove-skip-legacy
Labels: automerge, enhancement

#537 Update dependency: deps/kevm_release
  deps/k_release
  deps/kevm_release
  flake.lock
  flake.nix
  package/version
  poetry.lock
  pyproject.toml
  src/kontrol/__init__.py
  src/tests/integration/test-data/show/AccountParamsTest.testDealConcrete().trace.expected
  src/tests/integration/test-data/show/AddConst.applyOp(uint256).cse.expected
  src/tests/integration/test-data/show/AddrTest.test_addr_true().trace.expected
  src/tests/integration/test-data/show/ArithmeticCallTest.test_double_add(uint256,uint256).cse.expected
  src/tests/integration/test-data/show/ArithmeticCallTest.test_double_add_double_sub(uint256,uint256).cse.expected
  src/tests/integration/test-data/show/ArithmeticCallTest.test_double_add_sub_external(uint256,uint256,uint256).cse.expected
  src/tests/integration/test-data/show/ArithmeticContract.add(uint256,uint256).cse.expected
  src/tests/integration/test-data/show/ArithmeticContract.add_sub_external(uint256,uint256,uint256).cse.expected
  src/tests/integration/test-data/show/AssertTest.checkFail_assert_false().expected
  src/tests/integration/test-data/show/AssertTest.testFail_assert_true().expected
  src/tests/integration/test-data/show/AssertTest.testFail_expect_revert().expected
  src/tests/integration/test-data/show/AssertTest.test_assert_false().expected
  src/tests/integration/test-data/show/AssertTest.test_assert_true().expected
  src/tests/integration/test-data/show/AssertTest.test_failing_branch(uint256).expected
  src/tests/integration/test-data/show/AssertTest.test_revert_branch(uint256,uint256).expected
  src/tests/integration/test-data/show/AssumeTest.testFail_assume_false(uint256,uint256).expected
  src/tests/integration/test-data/show/AssumeTest.testFail_assume_true(uint256,uint256).expected
  src/tests/integration/test-data/show/AssumeTest.test_assume_false(uint256,uint256).expected
  src/tests/integration/test-data/show/BlockParamsTest.testWarp(uint256).trace.expected
  src/tests/integration/test-data/show/CSETest.test_add_const(uint256,uint256).cse.expected
  src/tests/integration/test-data/show/CSETest.test_identity(uint256,uint256).cse.expected
  src/tests/integration/test-data/show/Identity.applyOp(uint256).cse.expected
  src/tests/integration/test-data/show/Identity.identity(uint256).cse.expected
  src/tests/integration/test-data/show/SetUpDeployTest.test_extcodesize().expected
  src/tests/integration/test-data/show/gas-abstraction.expected
  src/tests/integration/test-data/show/merge-loop-heads.expected
  src/tests/integration/test-data/show/minimized/AssertTest.testFail_expect_revert().expected
  src/tests/integration/test-data/show/minimized/AssertTest.test_assert_false().expected
  src/tests/integration/test-data/show/minimized/AssertTest.test_failing_branch(uint256).expected
  src/tests/integration/test-data/show/minimized/AssertTest.test_revert_branch(uint256,uint256).expected
  src/tests/integration/test-data/show/node-refutation.expected
  src/tests/integration/test-data/show/split-node.expected
  src/tests/integration/test_kontrol_cse.py
Labels: automerge

#538 Update dependency: deps/kevm_release
  deps/k_release
  deps/kevm_release
  flake.lock
  flake.nix
  package/version
  poetry.lock
  pyproject.toml
  src/kontrol/__init__.py
  src/tests/integration/test-data/show/AccountParamsTest.testDealConcrete().trace.expected
  src/tests/integration/test-data/show/AddConst.applyOp(uint256).cse.expected
  src/tests/integration/test-data/show/AddrTest.test_addr_true().trace.expected
  src/tests/integration/test-data/show/ArithmeticCallTest.test_double_add(uint256,uint256).cse.expected
  src/tests/integration/test-data/show/ArithmeticCallTest.test_double_add_double_sub(uint256,uint256).cse.expected
  src/tests/integration/test-data/show/ArithmeticCallTest.test_double_add_sub_external(uint256,uint256,uint256).cse.expected
  src/tests/integration/test-data/show/ArithmeticContract.add(uint256,uint256).cse.expected
  src/tests/integration/test-data/show/ArithmeticContract.add_sub_external(uint256,uint256,uint256).cse.expected
  src/tests/integration/test-data/show/AssertTest.checkFail_assert_false().expected
  src/tests/integration/test-data/show/AssertTest.testFail_assert_true().expected
  src/tests/integration/test-data/show/AssertTest.testFail_expect_revert().expected
  src/tests/integration/test-data/show/AssertTest.test_assert_false().expected
  src/tests/integration/test-data/show/AssertTest.test_assert_true().expected
  src/tests/integration/test-data/show/AssertTest.test_failing_branch(uint256).expected
  src/tests/integration/test-data/show/AssertTest.test_revert_branch(uint256,uint256).expected
  src/tests/integration/test-data/show/AssumeTest.testFail_assume_false(uint256,uint256).expected
  src/tests/integration/test-data/show/AssumeTest.testFail_assume_true(uint256,uint256).expected
  src/tests/integration/test-data/show/AssumeTest.test_assume_false(uint256,uint256).expected
  src/tests/integration/test-data/show/BlockParamsTest.testWarp(uint256).trace.expected
  src/tests/integration/test-data/show/CSETest.test_add_const(uint256,uint256).cse.expected
  src/tests/integration/test-data/show/CSETest.test_identity(uint256,uint256).cse.expected
  src/tests/integration/test-data/show/Identity.applyOp(uint256).cse.expected
  src/tests/integration/test-data/show/Identity.identity(uint256).cse.expected
  src/tests/integration/test-data/show/SetUpDeployTest.test_extcodesize().expected
  src/tests/integration/test-data/show/gas-abstraction.expected
  src/tests/integration/test-data/show/merge-loop-heads.expected
  src/tests/integration/test-data/show/minimized/AssertTest.testFail_expect_revert().expected
  src/tests/integration/test-data/show/minimized/AssertTest.test_assert_false().expected
  src/tests/integration/test-data/show/minimized/AssertTest.test_failing_branch(uint256).expected
  src/tests/integration/test-data/show/minimized/AssertTest.test_revert_branch(uint256,uint256).expected
  src/tests/integration/test-data/show/node-refutation.expected
  src/tests/integration/test-data/show/split-node.expected
Labels: automerge
