Repository runtimeverification/kontrol, pull requests merged in 2024-09, with the labels that each got.

#803 Move helper functions to utils file
  src/kontrol/__main__.py
  src/kontrol/utils.py
Labels: automerge

#804 Update dependency: deps/kevm_release
  deps/kevm_release
  flake.lock
  flake.nix
  poetry.lock
  pyproject.toml
Labels: automerge

#806 Update dependency: deps/kevm_release
  deps/k_release
  deps/kevm_release
  flake.lock
  flake.nix
  poetry.lock
  pyproject.toml
Labels: automerge

#807 Update dependency: deps/kevm_release
  deps/kevm_release
  flake.lock
  flake.nix
  poetry.lock
  pyproject.toml
Labels: automerge

#810 Update dependency: deps/kevm_release
  deps/k_release
  deps/kevm_release
  flake.lock
  flake.nix
  poetry.lock
  pyproject.toml
  src/kontrol/kdist/kontrol_lemmas.md
Labels: automerge

#814 Fixed `--init-node-from-diff` and `init-node-from-dump`
  src/kontrol/options.py
Labels: bug

#815 Allow failing tests when updating expected output
  .github/workflows/update-expected-output.yml
Labels: automerge

#816 update-expected-output.yml: use force-sequential
  .github/workflows/update-expected-output.yml
Labels: automerge, enhancement

#819 Add support for setArbitraryStorage
  src/kontrol/kdist/cheatcodes.md
Labels: automerge

#820 Source maps improvement & Update expected output job fix
  .github/workflows/update-expected-output.yml
  poetry.lock
  pyproject.toml
  src/kontrol/__main__.py
  src/kontrol/foundry.py
  src/kontrol/solc.py
  src/tests/integration/test-data/show/AccountParamsTest.testDealConcrete().trace.expected
  src/tests/integration/test-data/show/AddConst.applyOp(uint256).cse.expected
  src/tests/integration/test-data/show/AddrTest.test_addr_true().trace.expected
  src/tests/integration/test-data/show/ArithmeticCallTest.test_double_add(uint256,uint256).cse.expected
  src/tests/integration/test-data/show/ArithmeticCallTest.test_double_add_double_sub(uint256,uint256).cse.expected
  src/tests/integration/test-data/show/ArithmeticCallTest.test_double_add_sub_external(uint256,uint256,uint256).cse.expected
  src/tests/integration/test-data/show/ArithmeticContract.add(uint256,uint256).cse.expected
  src/tests/integration/test-data/show/ArithmeticContract.add_sub_external(uint256,uint256,uint256).cse.expected
  src/tests/integration/test-data/show/AssertTest.checkFail_assert_false().expected
  src/tests/integration/test-data/show/AssertTest.testFail_assert_true().expected
  src/tests/integration/test-data/show/AssertTest.testFail_expect_revert().expected
  src/tests/integration/test-data/show/AssertTest.test_assert_false().expected
  src/tests/integration/test-data/show/AssertTest.test_assert_true().expected
  src/tests/integration/test-data/show/AssertTest.test_failing_branch(uint256).expected
  src/tests/integration/test-data/show/AssertTest.test_revert_branch(uint256,uint256).expected
  src/tests/integration/test-data/show/AssumeTest.testFail_assume_false(uint256,uint256).expected
  src/tests/integration/test-data/show/AssumeTest.testFail_assume_true(uint256,uint256).expected
  src/tests/integration/test-data/show/AssumeTest.test_assume_false(uint256,uint256).expected
  src/tests/integration/test-data/show/BlockParamsTest.testWarp(uint256).trace.expected
  src/tests/integration/test-data/show/CSETest.test_add_const(uint256,uint256).cse.expected
  src/tests/integration/test-data/show/CSETest.test_identity(uint256,uint256).cse.expected
  src/tests/integration/test-data/show/CallableStorageContract.str().cse.expected
  src/tests/integration/test-data/show/CallableStorageTest.test_str().cse.expected
  src/tests/integration/test-data/show/ConstructorTest.init.cse.expected
  src/tests/integration/test-data/show/ConstructorTest.test_contract_call().cse.expected
  src/tests/integration/test-data/show/ContractFieldTest.testEscrowToken().cse.expected
  src/tests/integration/test-data/show/Enum.enum_argument_range(uint8).cse.expected
  src/tests/integration/test-data/show/Enum.enum_storage_range().cse.expected
  src/tests/integration/test-data/show/Identity.applyOp(uint256).cse.expected
  src/tests/integration/test-data/show/Identity.identity(uint256).cse.expected
  src/tests/integration/test-data/show/ImportedContract.add(uint256).cse.expected
  src/tests/integration/test-data/show/ImportedContract.count().cse.expected
  src/tests/integration/test-data/show/ImportedContract.init.cse.expected
  src/tests/integration/test-data/show/ImportedContract.set(uint256).cse.expected
  src/tests/integration/test-data/show/InterfaceTagTest.testInterface().cse.expected
  src/tests/integration/test-data/show/SetUpDeployTest.test_extcodesize().expected
  src/tests/integration/test-data/show/StaticCallContract.set(uint256).cse.expected
  src/tests/integration/test-data/show/TGovernance.getEscrowTokenTotalSupply().cse.expected
  src/tests/integration/test-data/show/gas-abstraction.expected
  src/tests/integration/test-data/show/merge-loop-heads.expected
  src/tests/integration/test-data/show/minimized/AssertTest.testFail_expect_revert().expected
  src/tests/integration/test-data/show/minimized/AssertTest.test_assert_false().expected
  src/tests/integration/test-data/show/minimized/AssertTest.test_failing_branch(uint256).expected
  src/tests/integration/test-data/show/minimized/AssertTest.test_revert_branch(uint256,uint256).expected
  src/tests/integration/test-data/show/node-refutation.expected
  src/tests/integration/test-data/show/split-node.expected
Labels: automerge

#825 Use `build_info_path` in `load_build_info`, update TOML parsing logic
  src/kontrol/__main__.py
  src/kontrol/foundry.py
  src/kontrol/solc.py
Labels: automerge, bug

#832 Update dependency: deps/kevm_release
  deps/kevm_release
  flake.lock
  flake.nix
  poetry.lock
  pyproject.toml
Labels: automerge

#835 Update dependency: deps/kevm_release
  deps/k_release
  deps/kevm_release
  flake.lock
  flake.nix
  poetry.lock
  pyproject.toml
Labels: automerge

#836 Update dependency: deps/kevm_release
  deps/k_release
  deps/kevm_release
  flake.lock
  flake.nix
  poetry.lock
  pyproject.toml
Labels: automerge

#837 Update dependency: deps/kevm_release
  deps/k_release
  deps/kevm_release
  flake.lock
  flake.nix
  poetry.lock
  pyproject.toml
Labels: automerge

#840 allow consecutive startPranks
  src/kontrol/kdist/cheatcodes.md
  src/tests/integration/test-data/foundry-prove-skip-legacy
  src/tests/integration/test-data/foundry/test/PlainPrankTest.t.sol
  src/tests/integration/test-data/show/contracts.k.expected
Labels: automerge
