Repository runtimeverification/kontrol, pull requests merged in 2024-03, with the labels that each got.

#402 Update dependency: deps/kevm_release
  deps/k_release
  deps/kevm_release
  flake.lock
  flake.nix
  package/test-project/foundry.toml
  package/version
  poetry.lock
  pyproject.toml
  src/kontrol/__init__.py
  src/kontrol/__main__.py
  src/kontrol/foundry.py
  src/kontrol/prove.py
  src/kontrol/solc_to_k.py
  src/tests/integration/test-data/show/ArithmeticCallTest.test_double_add(uint256,uint256).expected
  src/tests/integration/test-data/show/AssertTest.checkFail_assert_false().expected
  src/tests/integration/test-data/show/AssertTest.testFail_assert_true().expected
  src/tests/integration/test-data/show/AssertTest.testFail_expect_revert().expected
  src/tests/integration/test-data/show/AssertTest.test_assert_false().expected
  src/tests/integration/test-data/show/AssertTest.test_assert_true().expected
  src/tests/integration/test-data/show/AssertTest.test_failing_branch(uint256).expected
  src/tests/integration/test-data/show/AssertTest.test_revert_branch(uint256,uint256).expected
  src/tests/integration/test-data/show/AssumeTest.testFail_assume_false(uint256,uint256).expected
  src/tests/integration/test-data/show/AssumeTest.testFail_assume_true(uint256,uint256).expected
  src/tests/integration/test-data/show/AssumeTest.test_assume_false(uint256,uint256).expected
  src/tests/integration/test-data/show/SetUpDeployTest.test_extcodesize().expected
  src/tests/integration/test-data/show/contracts.k.expected
  src/tests/integration/test-data/show/gas-abstraction.expected
  src/tests/integration/test-data/show/node-refutation.expected
  src/tests/integration/test_foundry_prove.py
  src/tests/unit/test-data/foundry-list/foundry-list.expected
Labels: automerge

#401 Refactor NatSpec tags for dynamic types
  package/version
  pyproject.toml
  src/kontrol/__init__.py
  src/kontrol/solc_to_k.py
  src/tests/integration/test-data/foundry/test/DynamicTypes.t.sol
  src/tests/integration/test-data/show/contracts.k.expected
  src/tests/unit/test_solc_to_k.py
Labels: automerge

#405 Update dependency: deps/kevm_release
  deps/k_release
  deps/kevm_release
  flake.lock
  flake.nix
  package/version
  poetry.lock
  pyproject.toml
  src/kontrol/__init__.py
  src/kontrol/solc_to_k.py
  src/tests/integration/test-data/show/contracts.k.expected
  src/tests/unit/test_solc_to_k.py
Labels: automerge

#377 Generate xml report
  package/version
  pyproject.toml
  src/kontrol/__init__.py
  src/kontrol/__main__.py
  src/kontrol/foundry.py
  src/kontrol/prove.py
  src/tests/integration/test_foundry_prove.py
Labels: automerge, enhancement, engagement

#406 Refactor get_test_id to fetch latest version
  package/version
  pyproject.toml
  src/kontrol/__init__.py
  src/kontrol/foundry.py
  src/tests/unit/test_get_test_id.py
Labels: automerge, enhancement

#408 Remove upper bound from pytest version
  package/version
  poetry.lock
  pyproject.toml
  src/kontrol/__init__.py
Labels: automerge

#410 Update dependency: deps/kevm_release
  deps/k_release
  deps/kevm_release
  flake.lock
  flake.nix
  package/version
  poetry.lock
  pyproject.toml
  src/kontrol/__init__.py
  src/tests/integration/test-data/show/ArithmeticCallTest.test_double_add(uint256,uint256).expected
  src/tests/integration/test-data/show/AssertTest.checkFail_assert_false().expected
  src/tests/integration/test-data/show/AssertTest.testFail_assert_true().expected
  src/tests/integration/test-data/show/AssertTest.testFail_expect_revert().expected
  src/tests/integration/test-data/show/AssertTest.test_assert_false().expected
  src/tests/integration/test-data/show/AssertTest.test_assert_true().expected
  src/tests/integration/test-data/show/AssertTest.test_failing_branch(uint256).expected
  src/tests/integration/test-data/show/AssertTest.test_revert_branch(uint256,uint256).expected
  src/tests/integration/test-data/show/AssumeTest.testFail_assume_false(uint256,uint256).expected
  src/tests/integration/test-data/show/AssumeTest.testFail_assume_true(uint256,uint256).expected
  src/tests/integration/test-data/show/AssumeTest.test_assume_false(uint256,uint256).expected
  src/tests/integration/test-data/show/SetUpDeployTest.test_extcodesize().expected
  src/tests/integration/test-data/show/gas-abstraction.expected
  src/tests/integration/test-data/show/node-refutation.expected
  src/tests/integration/test_foundry_prove.py
  src/tests/unit/test-data/foundry-list/foundry-list.expected
Labels: automerge

#391 print proof execution time after proof status
  package/version
  pyproject.toml
  src/kontrol/__init__.py
  src/kontrol/__main__.py
Labels: automerge, enhancement

#417 Update dependency: deps/kevm_release
  deps/kevm_release
  flake.lock
  flake.nix
  package/version
  poetry.lock
  pyproject.toml
  src/kontrol/__init__.py
Labels: automerge

#419 Update dependency: deps/kevm_release
  deps/kevm_release
  flake.lock
  flake.nix
  package/version
  poetry.lock
  pyproject.toml
  src/kontrol/__init__.py
Labels: automerge

#420 Update dependency: deps/kevm_release
  deps/kevm_release
  flake.lock
  flake.nix
  package/version
  poetry.lock
  pyproject.toml
  src/kontrol/__init__.py
Labels: automerge

#421 Update dependency: deps/kevm_release
  deps/kevm_release
  flake.lock
  flake.nix
  package/version
  poetry.lock
  pyproject.toml
  src/kontrol/__init__.py
Labels: automerge

#422 Update dependency: deps/kevm_release
  deps/kevm_release
  flake.lock
  flake.nix
  package/version
  poetry.lock
  pyproject.toml
  src/kontrol/__init__.py
Labels: automerge

#412 Implement `kontrol split-node` command
  package/version
  pyproject.toml
  src/kontrol/__init__.py
  src/kontrol/__main__.py
  src/kontrol/foundry.py
  src/tests/integration/test-data/foundry/test/PrankTest.t.sol
  src/tests/integration/test-data/show/contracts.k.expected
  src/tests/integration/test-data/show/split-node.expected
  src/tests/integration/test_foundry_prove.py
Labels: automerge

#427 Structural changes to execution of non-tests
  package/version
  pyproject.toml
  src/kontrol/__init__.py
  src/kontrol/foundry.py
  src/kontrol/prove.py
  src/tests/integration/test-data/cse-lemmas.k
  src/tests/integration/test-data/show/AssertTest.checkFail_assert_false().expected
  src/tests/integration/test-data/show/AssertTest.testFail_assert_true().expected
  src/tests/integration/test-data/show/AssertTest.testFail_expect_revert().expected
  src/tests/integration/test-data/show/AssertTest.test_assert_false().expected
  src/tests/integration/test-data/show/AssertTest.test_assert_true().expected
  src/tests/integration/test-data/show/AssertTest.test_failing_branch(uint256).expected
  src/tests/integration/test-data/show/AssertTest.test_revert_branch(uint256,uint256).expected
  src/tests/integration/test-data/show/AssumeTest.testFail_assume_false(uint256,uint256).expected
  src/tests/integration/test-data/show/AssumeTest.testFail_assume_true(uint256,uint256).expected
  src/tests/integration/test-data/show/AssumeTest.test_assume_false(uint256,uint256).expected
  src/tests/integration/test-data/show/SetUpDeployTest.test_extcodesize().expected
  src/tests/integration/test-data/show/foundry.k.expected
  src/tests/integration/test-data/show/gas-abstraction.expected
  src/tests/integration/test-data/show/node-refutation.expected
  src/tests/integration/test-data/show/split-node.expected
  src/tests/integration/test_foundry_prove.py
Labels: automerge, enhancement

#424 Fix failing case of expectEmit
  package/version
  pyproject.toml
  src/kontrol/__init__.py
  src/kontrol/kdist/cheatcodes.md
  src/tests/integration/test-data/foundry-prove-all
  src/tests/integration/test-data/foundry/test/EmitContractTest.t.sol
  src/tests/integration/test-data/show/contracts.k.expected
Labels: automerge, bug

#429 Update dependency: deps/kevm_release
  .github/workflows/Dockerfile
  deps/k_release
  deps/kevm_release
  flake.lock
  flake.nix
  package/version
  poetry.lock
  pyproject.toml
  src/kontrol/__init__.py
  src/tests/integration/test-data/show/ArithmeticCallTest.test_double_add(uint256,uint256).expected
  src/tests/integration/test-data/show/ArithmeticCallTest.test_double_add_double_sub(uint256,uint256).expected
  src/tests/integration/test-data/show/AssertTest.test_failing_branch(uint256).expected
  src/tests/integration/test-data/show/AssertTest.test_revert_branch(uint256,uint256).expected
  src/tests/integration/test-data/show/node-refutation.expected
  src/tests/integration/test-data/show/split-node.expected
  src/tests/profiling/test-data/foundry/foundry.toml
Labels: automerge

#428 Fix `xml-test-report`: allow proofs to be in nested directories
  package/version
  pyproject.toml
  src/kontrol/__init__.py
  src/kontrol/foundry.py
  src/tests/integration/test-data/foundry/test/nested/SimpleNested.t.sol
  src/tests/integration/test-data/show/contracts.k.expected
  src/tests/integration/test-data/show/foundry.k.expected
  src/tests/integration/test_foundry_prove.py
Labels: automerge, bug, engagement

#430 cheatcodes.md: use buf instead of bufStrict in freshUInt
  package/version
  pyproject.toml
  src/kontrol/__init__.py
  src/kontrol/kdist/cheatcodes.md
Labels: automerge, enhancement

#433 Refactor forge build process in test_foundry_prove
  package/version
  pyproject.toml
  src/kontrol/__init__.py
  src/tests/integration/test_foundry_prove.py
  src/tests/profiling/test_foundry_prove.py
  src/tests/utils.py
Labels: automerge, enhancement

#438 Update dependency: deps/kevm_release
  deps/kevm_release
  flake.lock
  flake.nix
  package/version
  poetry.lock
  pyproject.toml
  src/kontrol/__init__.py
  src/kontrol/__main__.py
Labels: automerge

#423 Print link to `foundry_success` predicate in `help_info`
  package/version
  pyproject.toml
  src/kontrol/__init__.py
  src/kontrol/foundry.py
  src/tests/integration/test-data/show/AssertTest.checkFail_assert_false().expected
  src/tests/integration/test-data/show/AssertTest.testFail_assert_true().expected
  src/tests/integration/test-data/show/AssertTest.testFail_expect_revert().expected
  src/tests/integration/test-data/show/AssertTest.test_assert_false().expected
  src/tests/integration/test-data/show/AssertTest.test_assert_true().expected
  src/tests/integration/test-data/show/AssertTest.test_failing_branch(uint256).expected
  src/tests/integration/test-data/show/AssertTest.test_revert_branch(uint256,uint256).expected
  src/tests/integration/test-data/show/AssumeTest.testFail_assume_false(uint256,uint256).expected
  src/tests/integration/test-data/show/AssumeTest.testFail_assume_true(uint256,uint256).expected
  src/tests/integration/test-data/show/AssumeTest.test_assume_false(uint256,uint256).expected
  src/tests/integration/test-data/show/SetUpDeployTest.test_extcodesize().expected
  src/tests/integration/test-data/show/gas-abstraction.expected
  src/tests/integration/test-data/show/node-refutation.expected
  src/tests/integration/test-data/show/split-node.expected
Labels: automerge, documentation

#439 Remove extra `s` in proof execution time
  package/version
  pyproject.toml
  src/kontrol/__init__.py
  src/kontrol/__main__.py
Labels: automerge

#436 CI task for CSE
  .github/workflows/test-pr.yml
  .gitignore
  package/version
  pyproject.toml
  src/kontrol/__init__.py
  src/tests/integration/test-data/foundry-dependency-skip
  src/tests/integration/test-data/show/ArithmeticCallTest.test_double_add(uint256,uint256).cse.expected
  src/tests/integration/test-data/show/ArithmeticCallTest.test_double_add_double_sub(uint256,uint256).cse.expected
  src/tests/integration/test-data/show/ArithmeticCallTest.test_double_add_sub_external(uint256,uint256,uint256).cse.expected
  src/tests/integration/test_foundry_prove.py
  src/tests/integration/test_kontrol_cse.py
  src/tests/integration/utils.py
Labels: automerge, enhancement

#404 Fix run-constructor option
  package/version
  pyproject.toml
  src/kontrol/__init__.py
  src/kontrol/prove.py
  src/kontrol/solc_to_k.py
  src/tests/integration/test-data/foundry-init-code
  src/tests/integration/test-data/foundry-prove-all
  src/tests/integration/test-data/foundry/test/ConstructorTest.t.sol
  src/tests/integration/test-data/show/ConstructorTest.run_constructor().expected
  src/tests/integration/test-data/show/contracts.k.expected
  src/tests/integration/test-data/show/foundry.k.expected
  src/tests/integration/test_foundry_prove.py
Labels: automerge, bug

#455 Add `@` symbol to escaped characters
  package/version
  pyproject.toml
  src/kontrol/__init__.py
  src/kontrol/solc_to_k.py
  src/tests/unit/test_solc_to_k.py
Labels: automerge

#449 Update dependency: deps/kevm_release
  deps/k_release
  deps/kevm_release
  flake.lock
  flake.nix
  package/version
  poetry.lock
  pyproject.toml
  src/kontrol/__init__.py
  src/tests/integration/test-data/show/AssertTest.testFail_expect_revert().expected
  src/tests/integration/test-data/show/AssumeTest.testFail_assume_false(uint256,uint256).expected
  src/tests/integration/test-data/show/AssumeTest.testFail_assume_true(uint256,uint256).expected
  src/tests/integration/test-data/show/AssumeTest.test_assume_false(uint256,uint256).expected
  src/tests/integration/test-data/show/split-node.expected
Labels: automerge

#403 Adds `--hevm` success predicate option to `kontrol prove`
  package/version
  pyproject.toml
  src/kontrol/__init__.py
  src/kontrol/__main__.py
  src/kontrol/foundry.py
  src/kontrol/hevm.py
  src/kontrol/kdist/foundry.md
  src/kontrol/kdist/hevm.md
  src/kontrol/options.py
  src/kontrol/prove.py
  src/tests/integration/conftest.py
  src/tests/integration/test-data/foundry/test/HevmTests.t.sol
  src/tests/integration/test-data/show/AssertTest.checkFail_assert_false().expected
  src/tests/integration/test-data/show/AssertTest.testFail_assert_true().expected
  src/tests/integration/test-data/show/AssertTest.testFail_expect_revert().expected
  src/tests/integration/test-data/show/AssertTest.test_assert_false().expected
  src/tests/integration/test-data/show/AssertTest.test_assert_true().expected
  src/tests/integration/test-data/show/AssertTest.test_failing_branch(uint256).expected
  src/tests/integration/test-data/show/AssertTest.test_revert_branch(uint256,uint256).expected
  src/tests/integration/test-data/show/AssumeTest.testFail_assume_false(uint256,uint256).expected
  src/tests/integration/test-data/show/AssumeTest.testFail_assume_true(uint256,uint256).expected
  src/tests/integration/test-data/show/AssumeTest.test_assume_false(uint256,uint256).expected
  src/tests/integration/test-data/show/SetUpDeployTest.test_extcodesize().expected
  src/tests/integration/test-data/show/contracts.k.expected
  src/tests/integration/test-data/show/foundry.k.expected
  src/tests/integration/test-data/show/gas-abstraction.expected
  src/tests/integration/test-data/show/merge-loop-heads.expected
  src/tests/integration/test-data/show/node-refutation.expected
  src/tests/integration/test-data/show/split-node.expected
  src/tests/integration/test_foundry_prove.py
  src/tests/integration/test_hevm_prove.py
  src/tests/integration/test_kontrol_cse.py
  src/tests/unit/test_foundry_list.py
  src/tests/unit/test_get_test_id.py
Labels: automerge, enhancement

#369 Upstream simplified Optimism test
  package/version
  pyproject.toml
  src/kontrol/__init__.py
  src/tests/integration/conftest.py
  src/tests/integration/test-data/foundry-prove-all
  src/tests/integration/test-data/foundry-prove-skip-legacy
  src/tests/integration/test-data/foundry/src/Portal.sol
  src/tests/integration/test-data/foundry/test/PortalTest.sol
  src/tests/integration/test-data/pausability-lemmas.k
  src/tests/integration/test-data/show/AssumeTest.testFail_assume_true(uint256,uint256).expected
  src/tests/integration/test-data/show/AssumeTest.test_assume_false(uint256,uint256).expected
  src/tests/integration/test-data/show/contracts.k.expected
  src/tests/integration/test-data/show/foundry.k.expected
Labels: automerge

#460 Removing non-CSE portion of CSE-related tests
  package/version
  pyproject.toml
  src/kontrol/__init__.py
  src/tests/integration/test-data/show/AddConst.applyOp(uint256).no-cse.expected
  src/tests/integration/test-data/show/ArithmeticCallTest.test_double_add(uint256,uint256).no-cse.expected
  src/tests/integration/test-data/show/ArithmeticCallTest.test_double_add_double_sub(uint256,uint256).no-cse.expected
  src/tests/integration/test-data/show/ArithmeticCallTest.test_double_add_sub_external(uint256,uint256,uint256).no-cse.expected
  src/tests/integration/test-data/show/Identity.applyOp(uint256).no-cse.expected
  src/tests/integration/test-data/show/Identity.identity(uint256).no-cse.expected
  src/tests/integration/test_kontrol_cse.py
Labels: automerge, enhancement

#456 Fix bug in `split` expression in `latest_proof_version`
  package/version
  pyproject.toml
  src/kontrol/__init__.py
  src/kontrol/foundry.py
  src/tests/unit/test_latest_proof_version.py
Labels: automerge

#453 Add better documentation to `kontrol prove` flags
  package/version
  pyproject.toml
  src/kontrol/__init__.py
  src/kontrol/cli.py
Labels: automerge, documentation

#345 Add solc 0.8.22
  flake.nix
  package/version
  pyproject.toml
  src/kontrol/__init__.py
Labels: automerge

#464 Update dependency: deps/kevm_release
  deps/kevm_release
  flake.lock
  flake.nix
  package/version
  poetry.lock
  pyproject.toml
  src/kontrol/__init__.py
Labels: automerge

#461 Display refuted nodes together with failure information
  package/version
  pyproject.toml
  src/kontrol/__init__.py
  src/kontrol/__main__.py
Labels: automerge

#462 Respect `NatSpec` lengths for `tuple[]` elements
  package/version
  pyproject.toml
  src/kontrol/__init__.py
  src/kontrol/solc_to_k.py
  src/tests/integration/test-data/foundry-prove-all
  src/tests/integration/test-data/foundry-prove-skip-legacy
  src/tests/integration/test-data/foundry/test/DynamicTypes.t.sol
  src/tests/integration/test-data/show/AssumeTest.test_assume_false(uint256,uint256).expected
  src/tests/integration/test-data/show/contracts.k.expected
Labels: automerge

#465 Update dependency: deps/kevm_release
  deps/k_release
  deps/kevm_release
  flake.lock
  flake.nix
  package/version
  poetry.lock
  pyproject.toml
  src/kontrol/__init__.py
Labels: automerge

#435 Added contribution guidelines file
  CONTRIBUTING.md
  package/version
  pyproject.toml
  src/kontrol/__init__.py
Labels: automerge, documentation

#468 Add Discord link in README
  README.md
  package/version
  pyproject.toml
  src/kontrol/__init__.py
Labels: automerge

#472 Make `break_on_calls`, `fail_fast`, `counterexample_information` consistent w/CLI
  package/version
  pyproject.toml
  src/kontrol/__init__.py
  src/kontrol/__main__.py
  src/kontrol/foundry.py
  src/kontrol/options.py
  src/tests/integration/test-data/show/gas-abstraction.expected
  src/tests/integration/test_foundry_prove.py
  src/tests/integration/test_kontrol_cse.py
  src/tests/profiling/test_foundry_prove.py
Labels: automerge

#470 Update dependency: deps/kevm_release
  .github/workflows/Dockerfile
  deps/kevm_release
  flake.lock
  flake.nix
  package/version
  poetry.lock
  pyproject.toml
  src/kontrol/__init__.py
Labels: automerge

#475 Update dependency: deps/kevm_release
  deps/k_release
  deps/kevm_release
  flake.lock
  flake.nix
  package/version
  poetry.lock
  pyproject.toml
  src/kontrol/__init__.py
  src/tests/integration/test-data/show/ArithmeticCallTest.test_double_add(uint256,uint256).cse.expected
  src/tests/integration/test-data/show/ArithmeticCallTest.test_double_add_double_sub(uint256,uint256).cse.expected
  src/tests/integration/test-data/show/ArithmeticCallTest.test_double_add_sub_external(uint256,uint256,uint256).cse.expected
  src/tests/integration/test-data/show/AssertTest.testFail_assert_true().expected
  src/tests/integration/test-data/show/AssertTest.testFail_expect_revert().expected
  src/tests/integration/test-data/show/AssertTest.test_assert_false().expected
  src/tests/integration/test-data/show/AssertTest.test_failing_branch(uint256).expected
  src/tests/integration/test-data/show/AssertTest.test_revert_branch(uint256,uint256).expected
  src/tests/integration/test-data/show/AssumeTest.testFail_assume_false(uint256,uint256).expected
  src/tests/integration/test-data/show/AssumeTest.test_assume_false(uint256,uint256).expected
  src/tests/integration/test-data/show/Identity.applyOp(uint256).cse.expected
  src/tests/integration/test-data/show/gas-abstraction.expected
Labels: automerge

#482 Update dependency: deps/kevm_release
  deps/kevm_release
  flake.lock
  flake.nix
  package/version
  poetry.lock
  pyproject.toml
  src/kontrol/__init__.py
Labels: automerge

#487 Add `build-info` to `forge build`
  package/test-project/foundry.toml
  package/version
  pyproject.toml
  src/kontrol/__init__.py
  src/kontrol/foundry.py
  src/tests/integration/test-data/foundry/foundry.toml
  src/tests/profiling/test-data/foundry/foundry.toml
Labels: automerge

#480 Corrections to how `setUp` and tests are connected
  package/version
  pyproject.toml
  src/kontrol/__init__.py
  src/kontrol/prove.py
  src/tests/integration/test-data/foundry-prove-all
  src/tests/integration/test-data/foundry/test/SetUpTest.t.sol
  src/tests/integration/test-data/show/ArithmeticCallTest.test_double_add(uint256,uint256).cse.expected
  src/tests/integration/test-data/show/ArithmeticCallTest.test_double_add_double_sub(uint256,uint256).cse.expected
  src/tests/integration/test-data/show/ArithmeticCallTest.test_double_add_sub_external(uint256,uint256,uint256).cse.expected
  src/tests/integration/test-data/show/AssertTest.checkFail_assert_false().expected
  src/tests/integration/test-data/show/AssertTest.testFail_assert_true().expected
  src/tests/integration/test-data/show/AssertTest.testFail_expect_revert().expected
  src/tests/integration/test-data/show/AssertTest.test_assert_false().expected
  src/tests/integration/test-data/show/AssertTest.test_assert_true().expected
  src/tests/integration/test-data/show/AssertTest.test_failing_branch(uint256).expected
  src/tests/integration/test-data/show/AssertTest.test_revert_branch(uint256,uint256).expected
  src/tests/integration/test-data/show/SetUpDeployTest.test_extcodesize().expected
  src/tests/integration/test-data/show/contracts.k.expected
  src/tests/integration/test-data/show/split-node.expected
  src/tests/integration/test_foundry_prove.py
Labels: automerge, enhancement

#477 Print claim in `kontrol refute-node`
  package/version
  pyproject.toml
  src/kontrol/__init__.py
  src/kontrol/__main__.py
  src/kontrol/foundry.py
Labels: automerge

#488 Update dependency: deps/kevm_release
  deps/k_release
  deps/kevm_release
  flake.lock
  flake.nix
  package/version
  poetry.lock
  pyproject.toml
  src/kontrol/__init__.py
Labels: automerge

#492 Update dependency: deps/kevm_release
  deps/k_release
  deps/kevm_release
  flake.lock
  flake.nix
  package/version
  poetry.lock
  pyproject.toml
  src/kontrol/__init__.py
Labels: automerge
