Repository runtimeverification/kontrol, pull requests merged in 2024-08, with the labels that each got.

#728 Add proof status bar
  src/kontrol/__main__.py
  src/kontrol/cli.py
  src/kontrol/options.py
  src/kontrol/prove.py
Labels: automerge

#736 Update dependency: deps/kevm_release
  deps/kevm_release
  flake.lock
  flake.nix
  poetry.lock
  pyproject.toml
Labels: automerge

#737 Update dependency: deps/kevm_release
  deps/kevm_release
  flake.lock
  flake.nix
  poetry.lock
  pyproject.toml
Labels: automerge

#731 Refactor digest checks.
  src/kontrol/foundry.py
  src/kontrol/kompile.py
  src/kontrol/solc_to_k.py
  src/kontrol/utils.py
Labels: automerge

#735 Add `--remove-old-proofs` command
  src/kontrol/cli.py
  src/kontrol/foundry.py
  src/kontrol/options.py
  src/kontrol/prove.py
Labels: automerge, enhancement, engagement

#741 Update dependency: deps/kevm_release
  deps/k_release
  deps/kevm_release
  flake.lock
  flake.nix
  poetry.lock
  pyproject.toml
Labels: automerge

#744 Update dependency: deps/kevm_release
  deps/k_release
  deps/kevm_release
  flake.lock
  flake.nix
  poetry.lock
  pyproject.toml
Labels: automerge

#746 Save BuildOptions attributes in digest file
  src/kontrol/kompile.py
  src/kontrol/options.py
Labels: kaas

#748 Update dependency: deps/kevm_release
  deps/k_release
  deps/kevm_release
  flake.lock
  flake.nix
  poetry.lock
  pyproject.toml
Labels: automerge

#749 Update dependency: deps/kevm_release
  deps/k_release
  deps/kevm_release
  flake.lock
  flake.nix
  poetry.lock
  pyproject.toml
Labels: automerge

#753 Update dependency: deps/kevm_release
  deps/kevm_release
  flake.lock
  flake.nix
  poetry.lock
  pyproject.toml
Labels: automerge

#754 Update dependency: deps/kevm_release
  deps/k_release
  deps/kevm_release
  flake.lock
  flake.nix
  poetry.lock
  pyproject.toml
Labels: automerge

#751 Add `--maintenance-rate` option
  src/kontrol/prove.py
Labels: automerge

#756 Update dependency: deps/kevm_release
  deps/k_release
  deps/kevm_release
  flake.lock
  flake.nix
  poetry.lock
  pyproject.toml
Labels: automerge

#759 Update dependency: deps/kevm_release
  deps/k_release
  deps/kevm_release
  flake.lock
  flake.nix
  poetry.lock
  pyproject.toml
Labels: automerge

#758 Adding support for `assume-defined` flag
  src/kontrol/prove.py
Labels: enhancement

#757 Add `require "foundry.md"` to `kontrol init` generated lemmas file
  src/kontrol/utils.py
Labels: automerge, bug, ux

#762 Update dependency: deps/kevm_release
  deps/k_release
  deps/kevm_release
  flake.lock
  flake.nix
  poetry.lock
  pyproject.toml
Labels: automerge

#755 Add proof cleaning capabilities to `kontrol clean`
  src/kontrol/__main__.py
  src/kontrol/cli.py
  src/kontrol/foundry.py
  src/kontrol/options.py
Labels: automerge, enhancement

#764 fix: `requires` instead of `require` for `kontrol init` lemmas.k
  src/kontrol/utils.py
  src/tests/integration/test_kontrol.py
Labels: bug

#426 Stabilising produced EVM code
  src/tests/integration/test-data/foundry/foundry.toml
  src/tests/integration/test-data/lemmas.k
  src/tests/integration/test-data/show/ConstructorTest.init.cse.expected
  src/tests/integration/test-data/show/ConstructorTest.test_contract_call().cse.expected
  src/tests/integration/test-data/show/Enum.init.cse.expected
  src/tests/integration/test-data/show/ImportedContract.init.cse.expected
  src/tests/integration/test-data/show/SetUpDeployTest.test_extcodesize().expected
  src/tests/integration/test-data/show/split-node.expected
Labels: automerge, enhancement, cse

#766 Update dependency: deps/kevm_release
  deps/k_release
  deps/kevm_release
  flake.lock
  flake.nix
  poetry.lock
  pyproject.toml
  src/kontrol/cli.py
  src/kontrol/foundry.py
  src/kontrol/options.py
  src/kontrol/prove.py
Labels: automerge

#767 Bringing back kore-rpc-command
  src/kontrol/cli.py
Labels: automerge, bug

#768 Update dependency: deps/kevm_release
  deps/kevm_release
  flake.lock
  flake.nix
  poetry.lock
  pyproject.toml
Labels: automerge

#765 copyStorage cheatcode
  .github/workflows/test-pr.yml
  src/kontrol/kdist/cheatcodes.md
  src/tests/integration/conftest.py
  src/tests/integration/test-data/foundry-prove-all
  src/tests/integration/test-data/foundry/test/CopyStorage.t.sol
  src/tests/integration/test-data/show/contracts.k.expected
  src/tests/integration/test-data/show/foundry.k.expected
Labels: automerge, enhancement

#769 CI flakiness fix: reduce `numprocesses` for integration tests
  .github/workflows/test-pr.yml
Labels: automerge

#771 Update dependency: deps/kevm_release
  deps/k_release
  deps/kevm_release
  flake.lock
  flake.nix
  poetry.lock
  pyproject.toml
Labels: automerge

#750 Fix/rework release tagging
  .github/workflows/master-push.yml
  .github/workflows/release.yml
  package/version.sh
Labels: automerge

#772 Update dependency: deps/z3
  deps/z3
Labels: automerge

#773 Update dependency: deps/kevm_release
  deps/k_release
  deps/kevm_release
  flake.lock
  flake.nix
  poetry.lock
  pyproject.toml
Labels: automerge

#774 Add new Kontrol CLI args
  src/kontrol/__main__.py
  src/kontrol/cli.py
  src/kontrol/options.py
  src/kontrol/utils.py
Labels: automerge, ux

#775 Update dependency: deps/kevm_release
  deps/k_release
  deps/kevm_release
  flake.lock
  flake.nix
  poetry.lock
  pyproject.toml
  src/tests/integration/test-data/show/AssumeTest.test_assume_false(uint256,uint256).expected
  src/tests/integration/test-data/show/gas-abstraction.expected
Labels: automerge

#778 Display command options on `--debug`
  src/kontrol/__main__.py
  src/kontrol/kompile.py
  src/kontrol/options.py
Labels: automerge, ux

#783 Workflow: Update test expected output
  .github/workflows/update-expected-output.yml
Labels: automerge, enhancement

#785 Fix permissions on `keccak.md`
  src/kontrol/kompile.py
Labels: automerge

#787 Revising init/pyproject file to show correct Major version on master branch
  pyproject.toml
  src/kontrol/__init__.py
Labels: automerge

#788 Update dependency: deps/kevm_release
  deps/kevm_release
  flake.lock
  flake.nix
  poetry.lock
  pyproject.toml
  src/kontrol/kdist/kontrol_lemmas.md
  src/tests/integration/test-data/cse-lemmas.k
  src/tests/integration/test-data/show/CallableStorageContract.str().cse.expected
  src/tests/integration/test-data/show/TGovernance.getEscrowTokenTotalSupply().cse.expected
Labels: automerge

#789 Update dependency: deps/kevm_release
  deps/k_release
  deps/kevm_release
  flake.lock
  flake.nix
  poetry.lock
  pyproject.toml
Labels: automerge

#790 Update dependency: deps/kevm_release
  deps/k_release
  deps/kevm_release
  flake.lock
  flake.nix
  poetry.lock
  pyproject.toml
Labels: automerge

#791 Update dependency: deps/kevm_release
  deps/kevm_release
  flake.lock
  flake.nix
  poetry.lock
  pyproject.toml
Labels: automerge

#792 Fix iterating over 'linkReferences' in solc to k
  src/kontrol/solc_to_k.py
Labels: bug

#794 Update dependency: deps/kevm_release
  deps/kevm_release
  flake.lock
  flake.nix
  poetry.lock
  pyproject.toml
Labels: automerge

#795 Add `funding.json` for OP Retro verification
  funding.json
Labels: automerge

#797 Update dependency: deps/kevm_release
  deps/k_release
  deps/kevm_release
  flake.lock
  flake.nix
  poetry.lock
  pyproject.toml
  src/kontrol/prove.py
Labels: automerge

#799 Update dependency: deps/kevm_release
  deps/kevm_release
  flake.lock
  flake.nix
  poetry.lock
  pyproject.toml
Labels: automerge

#802 Update dependency: deps/kevm_release
  deps/k_release
  deps/kevm_release
  flake.lock
  flake.nix
  poetry.lock
  pyproject.toml
Labels: automerge

#801 Add `--schedule` to `kontrol prove`
  src/kontrol/cli.py
  src/kontrol/options.py
  src/kontrol/prove.py
  src/tests/integration/test-data/show/AccountParamsTest.testDealConcrete().trace.expected
  src/tests/integration/test-data/show/AddConst.applyOp(uint256).cse.expected
  src/tests/integration/test-data/show/AddrTest.test_addr_true().trace.expected
  src/tests/integration/test-data/show/ArithmeticCallTest.test_double_add(uint256,uint256).cse.expected
  src/tests/integration/test-data/show/ArithmeticCallTest.test_double_add_double_sub(uint256,uint256).cse.expected
  src/tests/integration/test-data/show/ArithmeticCallTest.test_double_add_sub_external(uint256,uint256,uint256).cse.expected
  src/tests/integration/test-data/show/ArithmeticContract.add(uint256,uint256).cse.expected
  src/tests/integration/test-data/show/ArithmeticContract.add_sub_external(uint256,uint256,uint256).cse.expected
  src/tests/integration/test-data/show/AssertTest.checkFail_assert_false().expected
  src/tests/integration/test-data/show/AssertTest.testFail_assert_true().expected
  src/tests/integration/test-data/show/AssertTest.testFail_expect_revert().expected
  src/tests/integration/test-data/show/AssertTest.test_assert_false().expected
  src/tests/integration/test-data/show/AssertTest.test_assert_true().expected
  src/tests/integration/test-data/show/AssertTest.test_failing_branch(uint256).expected
  src/tests/integration/test-data/show/AssertTest.test_revert_branch(uint256,uint256).expected
  src/tests/integration/test-data/show/AssumeTest.testFail_assume_false(uint256,uint256).expected
  src/tests/integration/test-data/show/AssumeTest.testFail_assume_true(uint256,uint256).expected
  src/tests/integration/test-data/show/AssumeTest.test_assume_false(uint256,uint256).expected
  src/tests/integration/test-data/show/BlockParamsTest.testWarp(uint256).trace.expected
  src/tests/integration/test-data/show/CSETest.test_add_const(uint256,uint256).cse.expected
  src/tests/integration/test-data/show/CSETest.test_identity(uint256,uint256).cse.expected
  src/tests/integration/test-data/show/CallableStorageContract.str().cse.expected
  src/tests/integration/test-data/show/CallableStorageTest.test_str().cse.expected
  src/tests/integration/test-data/show/ConstructorTest.init.cse.expected
  src/tests/integration/test-data/show/ConstructorTest.test_contract_call().cse.expected
  src/tests/integration/test-data/show/ContractFieldTest.testEscrowToken().cse.expected
  src/tests/integration/test-data/show/Enum.enum_argument_range(uint8).cse.expected
  src/tests/integration/test-data/show/Enum.enum_storage_range().cse.expected
  src/tests/integration/test-data/show/Enum.init.cse.expected
  src/tests/integration/test-data/show/Identity.applyOp(uint256).cse.expected
  src/tests/integration/test-data/show/Identity.identity(uint256).cse.expected
  src/tests/integration/test-data/show/ImportedContract.add(uint256).cse.expected
  src/tests/integration/test-data/show/ImportedContract.count().cse.expected
  src/tests/integration/test-data/show/ImportedContract.init.cse.expected
  src/tests/integration/test-data/show/ImportedContract.set(uint256).cse.expected
  src/tests/integration/test-data/show/InterfaceTagTest.testInterface().cse.expected
  src/tests/integration/test-data/show/SetUpDeployTest.test_extcodesize().expected
  src/tests/integration/test-data/show/StaticCallContract.set(uint256).cse.expected
  src/tests/integration/test-data/show/TGovernance.getEscrowTokenTotalSupply().cse.expected
  src/tests/integration/test-data/show/gas-abstraction.expected
  src/tests/integration/test-data/show/merge-loop-heads.expected
  src/tests/integration/test-data/show/minimized/AssertTest.testFail_expect_revert().expected
  src/tests/integration/test-data/show/minimized/AssertTest.test_assert_false().expected
  src/tests/integration/test-data/show/minimized/AssertTest.test_failing_branch(uint256).expected
  src/tests/integration/test-data/show/minimized/AssertTest.test_revert_branch(uint256,uint256).expected
  src/tests/integration/test-data/show/node-refutation.expected
  src/tests/integration/test-data/show/split-node.expected
  src/tests/integration/test_foundry_prove.py
  src/tests/integration/test_kontrol.py
Labels: automerge
